// PlainSlang data access — dual-runtime.
//
//  Runtime A (Node: local dev, Docker) ─ uses `pg` over DATABASE_URL.
//  Runtime B (Cloudflare Workers via OpenNext) ─ uses Supabase's HTTP API
//    (supabase-js) with the service-role key; no TCP sockets, no LISTEN.
//
//  Realtime:
//    Node runtime  → SSE (/api/stream) fed by pg LISTEN/NOTIFY (lib/db.js).
//    Edge runtime  → browsers subscribe DIRECTLY to Supabase Realtime over
//    WebSockets (lib/useLive.js picks the transport automatically).
//
//  Which mode is active is decided once per process:
//    SUPABASE_URL + SUPABASE_SERVICE_ROLE_KEY set  → supabase mode
//    else DATABASE_URL                             → pg mode

import { createClient } from '@supabase/supabase-js';

export const MODE =
  process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY
    ? 'supabase'
    : process.env.DATABASE_URL
      ? 'pg'
      : 'static'; // no DB configured: serve the committed site/data.json read-only

const g = globalThis.__plainslangData || (globalThis.__plainslangData = {});

export function getSupabase() {
  if (!g.supabase) {
    g.supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_SERVICE_ROLE_KEY,
      { auth: { persistSession: false }, realtime: { params: {} } }
    );
  }
  return g.supabase;
}

// ---------------------------------------------------------------------------
// STATIC read-only mode: no DATABASE_URL and no Supabase vars. Loads the
// committed site/data.json (the static edition's daily-verified snapshot) and
// serves all reads from memory. Writes are rejected with READ_ONLY so the
// deployment still works with zero configuration.
// ---------------------------------------------------------------------------
import staticData from '../site/data.json';

function loadStaticStore() {
  if (g.staticStore) return g.staticStore;
  // Bundled at build time (works on Node AND Cloudflare Workers, where there
  // is no filesystem). site/data.json is regenerated by the daily GitHub
  // Action, and every push triggers a redeploy, so the bundle stays fresh.
  const d = staticData;
  const rows = d.terms.map((t) => ({
    id: t.id, term: t.term, emoji: t.emoji, definition: t.definition,
    example: t.example, notes: t.notes, age_group: t.ageGroup,
    difficulty: t.difficulty, say: t.say, source_name: t.sourceName,
    source_url: t.sourceUrl, tags: JSON.stringify(t.tags || []),
    is_woty: t.isWoty ? 1 : 0, trending: t.trending ? 1 : 0,
    trending_evidence: t.trendingEvidence ? JSON.stringify(t.trendingEvidence) : null,
    is_seed: t.isSeed === false ? 0 : 1, category: t.category || 'teen',
    related: JSON.stringify(t.related || []),
    created_at: d.generatedAt, updated_at: d.generatedAt,
  }));
  const meta = new Map();
  if (d.trendingSnapshot) meta.set('trending_status', JSON.stringify(d.trendingSnapshot));
  if (d.radarSnapshot) meta.set('radar_status', JSON.stringify(d.radarSnapshot));
  g.staticStore = { rows, meta, generatedAt: d.generatedAt };
  return g.staticStore;
}

function readOnlyError() {
  const e = new Error('This deployment is read-only (no database configured). Terms are managed in the repo.');
  e.code = 'READ_ONLY';
  return e;
}

// ---------------------------------------------------------------------------
// Row helpers (shared shape both modes return: snake_case DB rows)
// ---------------------------------------------------------------------------

export function rowToTerm(r) {
  return {
    id: r.id,
    term: r.term,
    emoji: r.emoji,
    definition: r.definition,
    example: r.example,
    notes: r.notes,
    ageGroup: r.age_group,
    difficulty: r.difficulty,
    say: r.say,
    sourceName: r.source_name,
    sourceUrl: r.source_url,
    tags: safeJson(r.tags, []),
    isWoty: !!r.is_woty,
    trending: !!r.trending,
    trendingEvidence: safeJson(r.trending_evidence, null),
    isSeed: !!r.is_seed,
    category: r.category || 'teen',
    related: safeJson(r.related, []),
    createdAt: r.created_at,
    updatedAt: r.updated_at,
  };
}

export function termToRow(clean, { isSeed = 0, now }) {
  return {
    term: clean.term,
    emoji: clean.emoji || '',
    definition: clean.definition,
    example: clean.example || null,
    notes: clean.notes || null,
    age_group: clean.ageGroup || 'gen_z',
    difficulty: clean.difficulty || 'medium',
    say: clean.say || null,
    source_name: clean.sourceName || null,
    source_url: clean.sourceUrl || null,
    tags: JSON.stringify(clean.tags || []),
    is_woty: 0,
    trending: 0,
    is_seed: isSeed,
    category: clean.category || 'teen',
    related: '[]',
    created_at: now,
    updated_at: now,
  };
}

function safeJson(s, fallback) {
  if (!s) return fallback;
  if (typeof s === 'object') return s; // PostgREST may return parsed jsonb
  try {
    return JSON.parse(s);
  } catch {
    return fallback;
  }
}

// ---------------------------------------------------------------------------
// Unified operations. Each has a pg path and a supabase path.
// pg path lazily imports ./db so the pg driver never loads on the edge.
// ---------------------------------------------------------------------------

export async function listTerms({ q, ageGroup, trending, category } = {}) {
  if (MODE === 'static') {
    const { rows } = loadStaticStore();
    const nq = q ? String(q).toLowerCase() : null;
    return rows
      .filter((r) => {
        if (category && !(r.category === category || JSON.parse(r.related).includes(category))) return false;
        if (ageGroup && r.age_group !== ageGroup) return false;
        if (trending && !r.trending) return false;
        if (nq) {
          const hay = `${r.term} ${r.definition} ${r.example || ''} ${r.tags}`.toLowerCase();
          if (!hay.includes(nq)) return false;
        }
        return true;
      })
      .sort((a, b) => a.term.toLowerCase().localeCompare(b.term.toLowerCase()))
      .map(rowToTerm);
  }
  if (MODE === 'pg') {
    const { query } = await import('./db');
    let sql = 'SELECT * FROM terms WHERE TRUE';
    const params = [];
    if (category) {
      params.push(category);
      const i = params.length;
      sql += ` AND (category = $${i} OR related::jsonb ? $${i})`;
    }
    if (q) {
      params.push(`%${q}%`);
      const i = params.length;
      sql += ` AND (term ILIKE $${i} OR definition ILIKE $${i} OR COALESCE(example,'') ILIKE $${i} OR COALESCE(tags,'') ILIKE $${i})`;
    }
    if (ageGroup) {
      params.push(ageGroup);
      sql += ` AND age_group = $${params.length}`;
    }
    if (trending) sql += ' AND trending = 1';
    sql += ' ORDER BY LOWER(term)';
    const { rows } = await query(sql, params);
    return rows.map(rowToTerm);
  }

  // supabase mode — PostgREST filters; category OR-related via or()
  // SECURITY: category/q are user-controlled query params. PostgREST or()
  // syntax treats , ( ) . as metacharacters, so (a) category is validated
  // against the fixed allowlist, (b) q is stripped of filter metacharacters
  // and PostgREST wildcards before interpolation.
  const CATEGORY_ALLOWLIST = new Set(['teen', 'texting', 'gaming', 'coding', 'corporate', 'safety', 'emoji']);
  const sb = getSupabase();
  let req = sb.from('terms').select('*');
  if (category) {
    if (!CATEGORY_ALLOWLIST.has(category)) return []; // unknown category: no rows, no injection
    req = req.or(`category.eq.${category},related.like.%"${category}"%`);
  }
  if (q) {
    const safeQ = String(q).replace(/[,()."'\\%_*]/g, ' ').trim().slice(0, 80);
    if (safeQ) {
      const like = `%${safeQ}%`;
      req = req.or(`term.ilike.${like},definition.ilike.${like},example.ilike.${like},tags.ilike.${like}`);
    }
  }
  if (ageGroup) req = req.eq('age_group', ageGroup);
  if (trending) req = req.eq('trending', 1);
  const { data, error } = await req.order('term', { ascending: true });
  if (error) throw new Error(error.message);
  return data.map(rowToTerm);
}

export async function getTerm(id) {
  if (MODE === 'static') {
    const row = loadStaticStore().rows.find((r) => r.id === id);
    return row ? rowToTerm(row) : null;
  }
  if (MODE === 'pg') {
    const { query } = await import('./db');
    const { rows } = await query('SELECT * FROM terms WHERE id = $1', [id]);
    return rows[0] ? rowToTerm(rows[0]) : null;
  }
  const { data, error } = await getSupabase().from('terms').select('*').eq('id', id).maybeSingle();
  if (error) throw new Error(error.message);
  return data ? rowToTerm(data) : null;
}

export async function createTerm(clean) {
  if (MODE === 'static') throw readOnlyError();
  const now = new Date().toISOString();
  const row = termToRow(clean, { now });
  if (MODE === 'pg') {
    const { query } = await import('./db');
    const cols = Object.keys(row);
    const vals = Object.values(row);
    const ph = cols.map((_, i) => `$${i + 1}`).join(',');
    const { rows } = await query(
      `INSERT INTO terms (${cols.join(',')}) VALUES (${ph}) RETURNING *`, vals);
    return rowToTerm(rows[0]);
  }
  const { data, error } = await getSupabase().from('terms').insert(row).select().single();
  if (error) throw new Error(error.message);
  return rowToTerm(data);
}

export async function updateTerm(id, clean, keepCategory) {
  if (MODE === 'static') throw readOnlyError();
  const patch = {
    term: clean.term, emoji: clean.emoji, definition: clean.definition,
    example: clean.example, notes: clean.notes, age_group: clean.ageGroup,
    difficulty: clean.difficulty, say: clean.say, source_name: clean.sourceName,
    source_url: clean.sourceUrl, tags: JSON.stringify(clean.tags || []),
    updated_at: new Date().toISOString(),
  };
  if (!keepCategory) patch.category = clean.category;
  if (MODE === 'pg') {
    const { query } = await import('./db');
    const cols = Object.keys(patch);
    const vals = Object.values(patch);
    const set = cols.map((c, i) => `${c} = $${i + 1}`).join(', ');
    const { rows } = await query(
      `UPDATE terms SET ${set} WHERE id = $${cols.length + 1} RETURNING *`, [...vals, id]);
    return rows[0] ? rowToTerm(rows[0]) : null;
  }
  const { data, error } = await getSupabase().from('terms').update(patch).eq('id', id).select().maybeSingle();
  if (error) throw new Error(error.message);
  return data ? rowToTerm(data) : null;
}

export async function deleteTerm(id) {
  if (MODE === 'static') throw readOnlyError();
  if (MODE === 'pg') {
    const { query } = await import('./db');
    const { rowCount, rows } = await query('DELETE FROM terms WHERE id = $1 RETURNING term', [id]);
    return rowCount > 0 ? rows[0].term : null;
  }
  const { data, error } = await getSupabase().from('terms').delete().eq('id', id).select('term').maybeSingle();
  if (error) throw new Error(error.message);
  return data ? data.term : null;
}

export async function getMeta(key) {
  if (MODE === 'static') return loadStaticStore().meta.get(key) ?? null;
  if (MODE === 'pg') {
    const { query } = await import('./db');
    const { rows } = await query('SELECT value FROM meta WHERE key = $1', [key]);
    return rows[0]?.value ?? null;
  }
  const { data, error } = await getSupabase().from('meta').select('value').eq('key', key).maybeSingle();
  if (error) throw new Error(error.message);
  return data?.value ?? null;
}

export async function setMeta(key, value) {
  if (MODE === 'static') { loadStaticStore().meta.set(key, value); return; } // in-memory only
  if (MODE === 'pg') {
    const { query } = await import('./db');
    await query(
      `INSERT INTO meta (key, value) VALUES ($1, $2)
       ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value`, [key, value]);
    return;
  }
  const { error } = await getSupabase().from('meta').upsert({ key, value });
  if (error) throw new Error(error.message);
}

export async function counts() {
  if (MODE === 'static') {
    const { rows } = loadStaticStore();
    return {
      total: rows.length,
      seeded: rows.filter((r) => r.is_seed).length,
      trending: rows.filter((r) => r.trending).length,
    };
  }
  if (MODE === 'pg') {
    const { query } = await import('./db');
    const total = (await query('SELECT COUNT(*)::int c FROM terms')).rows[0].c;
    const seeded = (await query('SELECT COUNT(*)::int c FROM terms WHERE is_seed = 1')).rows[0].c;
    const trending = (await query('SELECT COUNT(*)::int c FROM terms WHERE trending = 1')).rows[0].c;
    return { total, seeded, trending };
  }
  const sb = getSupabase();
  const [t, s, tr] = await Promise.all([
    sb.from('terms').select('id', { count: 'exact', head: true }),
    sb.from('terms').select('id', { count: 'exact', head: true }).eq('is_seed', 1),
    sb.from('terms').select('id', { count: 'exact', head: true }).eq('trending', 1),
  ]);
  for (const r of [t, s, tr]) if (r.error) throw new Error(r.error.message);
  return { total: t.count, seeded: s.count, trending: tr.count };
}

// Bulk fetches used by trending/radar/stats/quiz
export async function allTermRows(filter = {}) {
  if (MODE === 'static') {
    let rows = loadStaticStore().rows;
    if (filter.category) rows = rows.filter((r) => r.category === filter.category);
    if (filter.isSeed !== undefined) rows = rows.filter((r) => !!r.is_seed === !!filter.isSeed);
    return [...rows].sort((a, b) => a.id - b.id);
  }
  if (MODE === 'pg') {
    const { query } = await import('./db');
    let sql = 'SELECT * FROM terms WHERE TRUE';
    const params = [];
    if (filter.category) {
      params.push(filter.category);
      sql += ` AND category = $${params.length}`;
    }
    if (filter.isSeed !== undefined) {
      params.push(filter.isSeed ? 1 : 0);
      sql += ` AND is_seed = $${params.length}`;
    }
    sql += ' ORDER BY id';
    return (await query(sql, params)).rows;
  }
  const sb = getSupabase();
  let req = sb.from('terms').select('*');
  if (filter.category) req = req.eq('category', filter.category);
  if (filter.isSeed !== undefined) req = req.eq('is_seed', filter.isSeed ? 1 : 0);
  const { data, error } = await req.order('id', { ascending: true }).limit(2000);
  if (error) throw new Error(error.message);
  return data;
}

export async function resetTrendingFlags(matches, wotyEvidence) {
  if (MODE === 'static') {
    // in-memory only: live verify still works, resets on restart (honest for a DB-less deploy)
    const { rows } = loadStaticStore();
    const byId = new Map(rows.map((r) => [r.id, r]));
    for (const r of rows) { r.trending = 0; r.trending_evidence = null; }
    for (const m of matches) {
      const r = byId.get(m.id);
      if (r) { r.trending = 1; r.trending_evidence = JSON.stringify({ headline: m.headline, link: m.link, feed: m.feed }); }
    }
    for (const r of rows) {
      if (r.is_woty) { r.trending = 1; r.trending_evidence = r.trending_evidence || JSON.stringify(wotyEvidence); }
    }
    return;
  }
  if (MODE === 'pg') {
    const { query } = await import('./db');
    await query('UPDATE terms SET trending = 0, trending_evidence = NULL');
    for (const m of matches) {
      await query('UPDATE terms SET trending = 1, trending_evidence = $1 WHERE id = $2',
        [JSON.stringify({ headline: m.headline, link: m.link, feed: m.feed }), m.id]);
    }
    await query(
      'UPDATE terms SET trending = 1, trending_evidence = COALESCE(trending_evidence, $1) WHERE is_woty = 1',
      [JSON.stringify(wotyEvidence)]);
    return;
  }
  const sb = getSupabase();
  let r = await sb.from('terms').update({ trending: 0, trending_evidence: null }).gte('id', 0);
  if (r.error) throw new Error(r.error.message);
  for (const m of matches) {
    r = await sb.from('terms')
      .update({ trending: 1, trending_evidence: JSON.stringify({ headline: m.headline, link: m.link, feed: m.feed }) })
      .eq('id', m.id);
    if (r.error) throw new Error(r.error.message);
  }
  // WOTY terms: set trending, keep an existing evidence if one was just written
  const { data: woty, error } = await sb.from('terms').select('id, trending_evidence').eq('is_woty', 1);
  if (error) throw new Error(error.message);
  for (const w of woty) {
    r = await sb.from('terms')
      .update({ trending: 1, trending_evidence: w.trending_evidence || JSON.stringify(wotyEvidence) })
      .eq('id', w.id);
    if (r.error) throw new Error(r.error.message);
  }
}

export async function trendingTerms() {
  if (MODE === 'static') {
    return loadStaticStore().rows
      .filter((r) => r.trending)
      .sort((a, b) => (b.is_woty - a.is_woty) || a.term.toLowerCase().localeCompare(b.term.toLowerCase()))
      .map(rowToTerm);
  }
  if (MODE === 'pg') {
    const { query } = await import('./db');
    const { rows } = await query(
      'SELECT * FROM terms WHERE trending = 1 ORDER BY is_woty DESC, LOWER(term)');
    return rows.map(rowToTerm);
  }
  const { data, error } = await getSupabase()
    .from('terms').select('*').eq('trending', 1)
    .order('is_woty', { ascending: false }).order('term', { ascending: true });
  if (error) throw new Error(error.message);
  return data.map(rowToTerm);
}

// Ensure schema+seed (pg mode only; supabase mode is seeded via script/SQL once)
export async function ensureReady() {
  if (MODE === 'static') { loadStaticStore(); return true; }
  if (MODE === 'pg') {
    const { ensureReady: pgReady } = await import('./db');
    return pgReady();
  }
  return true; // supabase project is provisioned by scripts/seed-supabase.mjs
}
