// Pack expansion v7 — 2025/2026 wave: AI-era safety threats, competitive-gaming
// culture, AI/dev vocabulary, workplace trends, and current teen slang.
// All Wiktionary titles verified via MediaWiki API 2026-09-04; Wikipedia pages
// verified HTTP 200. Unverifiable candidates were DROPPED, not guessed.

const WIKT = (w) => ({
  sourceName: `Wiktionary — ${w}`,
  sourceUrl: `https://en.wiktionary.org/wiki/${encodeURIComponent(w)}`,
});
const WIKI = (title, page) => ({
  sourceName: `Wikipedia — ${title}`,
  sourceUrl: `https://en.wikipedia.org/wiki/${page}`,
});

export const PACK_TERMS_V7 = [
  // ============ ⚠️ SAFETY — AI-era & current threats ============
  { category: 'safety', term: 'deepfake', emoji: '🎭', difficulty: 'medium', related: ['teen', 'coding'], definition: 'AI-generated fake video/audio of a real person. Teens encounter it as manipulated clips of classmates or celebrities — increasingly used in bullying and scams.', example: 'A “video” of a classmate that never happened.', tags: ['parent-alert', 'ai', 'harassment'], ...WIKT('deepfake') },
  { category: 'safety', term: 'nudify apps', emoji: '🚨', difficulty: 'medium', definition: 'AI tools that fabricate nude images from an ordinary clothed photo. Used in sextortion and school harassment cases; possessing/creating such images of minors is a crime in many places. The #1 new threat parents should know.', example: 'A yearbook photo run through an app becomes blackmail material.', tags: ['parent-alert', 'ai', 'sextortion', 'crime'], ...WIKI('Deepfake pornography', 'Deepfake_pornography') },
  { category: 'safety', term: 'pig butchering', emoji: '🐷', difficulty: 'hard', definition: 'A long-con scam: the scammer builds a fake friendship/romance over weeks (“fattening the pig”), then lures the victim into fake crypto investments. Now targets teens and young adults on social apps.', example: 'A friendly stranger DM that slowly turns to “investment tips.”', tags: ['parent-alert', 'scam', 'crypto'], ...WIKT('pig butchering') },
  { category: 'safety', term: 'romance scam', emoji: '💔', difficulty: 'easy', definition: 'Fake online relationship built to extract money or images. The teen version often precedes sextortion.', example: '“My online girlfriend needs gift cards” is not a girlfriend.', tags: ['parent-alert', 'scam'], ...WIKT('romance scam') },
  { category: 'safety', term: 'AI companion', emoji: '🤖', difficulty: 'medium', related: ['teen'], definition: 'Chatbot “friends/partners” (Character.AI-style) teens can bond with. Concerns: emotional dependence, adult content, and displacement of real relationships. Worth knowing which apps your kid talks to.', example: '“He spends hours talking to his AI girlfriend.”', tags: ['parent-alert', 'ai', 'mental-health'], ...WIKI('Chatbot', 'Chatbot') },
  { category: 'safety', term: 'Zyn', emoji: '🟢', difficulty: 'easy', definition: 'Nicotine pouch brand — smokeless, spitless, easy to hide in a lip. The post-vape nicotine wave among teen boys; “zynfluencers” push it online.', example: 'Small round tins in a backpack are worth a look.', tags: ['parent-alert', 'nicotine'], ...WIKT('Zyn') },
  { category: 'safety', term: 'galaxy gas', emoji: '🌌', difficulty: 'medium', definition: 'Flavored nitrous oxide canisters (whipped-cream chargers) inhaled for a high — a viral 2024–25 trend. Oxygen deprivation and nerve damage are real risks.', example: 'Colorful canisters marketed like candy on TikTok.', tags: ['parent-alert', 'inhalant', 'trend'], ...WIKI('Nitrous oxide (recreational use)', 'Nitrous_oxide#Recreational_use') },
  { category: 'safety', term: 'whippets', emoji: '💨', difficulty: 'medium', definition: 'Inhaling nitrous oxide from whipped-cream chargers. Old drug, new packaging (see galaxy gas).', example: 'Empty metal chargers in a car or room.', tags: ['parent-alert', 'inhalant'], ...WIKT('whippet') },
  { category: 'safety', term: 'chroming', emoji: '🥫', difficulty: 'hard', definition: 'Inhaling aerosols/solvents (deodorant, paint) for a high — the TikTok-era name for huffing. Has killed kids; several viral “challenge” waves.', example: 'Empty aerosol cans + dizzy spells = talk now.', tags: ['parent-alert', 'inhalant', 'trend'], ...WIKT('chroming') },
  { category: 'safety', term: 'borg', emoji: '🥛', difficulty: 'medium', related: ['teen'], definition: '“Blackout rage gallon” — a gallon jug of water, vodka, and electrolyte mix, individually carried at college parties. Framed as “safer drinking,” often just a lot of vodka.', example: 'Gallon jugs with joke names at a tailgate.', tags: ['parent-alert', 'alcohol', 'college'], ...WIKT('borg') },
  { category: 'safety', term: 'tianeptine', emoji: '⛽', difficulty: 'hard', definition: '“Gas-station heroin” — an opioid-like antidepressant sold in gas stations as a supplement (Neptune’s Fix, ZaZa Red). FDA-warned, addictive, and legal-ish in some states.', example: 'Tiny red bottles from the gas station counter.', tags: ['parent-alert', 'drugs', 'legal-gray'], ...WIKI('Tianeptine', 'Tianeptine') },
  { category: 'safety', term: 'fent', emoji: '☠️', difficulty: 'medium', definition: 'Fentanyl — the synthetic opioid behind most teen overdose deaths, usually hidden in counterfeit pills (“percs,” “blues”). One pill can kill; kids buying any pill online are at risk.', example: '“Perc 30s” from Snapchat are almost never real oxycodone.', tags: ['parent-alert', 'drugs', 'overdose'], ...WIKT('fent') },
  { category: 'safety', term: 'tranq', emoji: '🧟', difficulty: 'hard', definition: 'Xylazine — an animal tranquilizer cut into street fentanyl (“tranq dope”). Causes wounds and doesn’t respond to Narcan.', example: 'News reports on “zombie drug” refer to this.', tags: ['parent-alert', 'drugs'], ...WIKT('tranq') },
  { category: 'safety', term: 'Benadryl challenge', emoji: '💊', difficulty: 'medium', definition: 'Viral dare to take massive diphenhydramine doses to hallucinate. Caused teen deaths; resurfaces periodically on TikTok.', example: 'FDA issued warnings after hospitalizations.', tags: ['parent-alert', 'challenge', 'overdose'], ...WIKI('Benadryl — safety warnings', 'Benadryl') },
  { category: 'safety', term: 'One Chip Challenge', emoji: '🌶️', difficulty: 'easy', definition: 'Eating an extremely hot pepper chip (Paqui) on camera. Sent kids to hospitals; linked to a Massachusetts teen death in 2023 and pulled from shelves — copycats persist.', example: 'A single chip in a coffin-shaped box.', tags: ['parent-alert', 'challenge'], ...WIKI('Paqui One Chip Challenge', 'Paqui') },
  { category: 'safety', term: 'senior assassin', emoji: '🔫', difficulty: 'medium', related: ['teen'], definition: 'A live-action elimination game seniors play with water guns — harmless in theory, but police warn about realistic-looking blasters, trespassing, and ambushes near roads.', example: 'Kids in masks stalking a friend’s driveway at 11pm.', tags: ['trend', 'school', 'parent-aware'], ...WIKI('Assassin (game)', 'Assassin_(game)') },

  // ============ 🧃 TEEN — 2025/26 wave ============
  { category: 'teen', term: 'type shit', emoji: '🗣️', ageGroup: 'high_school', difficulty: 'hard', related: ['texting'], definition: 'Emphatic agreement — “exactly,” “real.” Often just “ts.” (Note: “ts” also means “this” in “ts pmo.”)', example: '“We eating good tonight.” “Type shit.”', tags: ['agreement', 'aave'], ...WIKT('type shit') },
  { category: 'teen', term: 'glizzy', emoji: '🌭', ageGroup: 'middle', difficulty: 'medium', definition: 'A hot dog. Yes, really. From DC slang (originally a gun), now 99% about hot dogs and the joke of eating one.', example: '“Grabbing a glizzy at the game.”', tags: ['food', 'humor'], ...WIKT('glizzy') },
  { category: 'teen', term: 'moots', emoji: '🤝', ageGroup: 'high_school', difficulty: 'medium', related: ['texting'], definition: 'Mutuals — people who follow you and you follow back. Your online circle.', example: '“One of my moots posted it first.”', tags: ['social-media'], ...WIKT('moots') },
  { category: 'teen', term: 'twin', emoji: '👯', ageGroup: 'high_school', difficulty: 'easy', definition: 'Best friend — someone so close you’re “twins.” Address term: “what’s good twin.”', example: '“I got you, twin.”', tags: ['friends', 'address'], ...WIKT('twin') },
  { category: 'teen', term: 'gng', emoji: '🫡', ageGroup: 'high_school', difficulty: 'hard', related: ['texting'], definition: '“Gang” — address term for a friend, like bro/twin. Texting-compressed.', example: '“wyd gng.”', tags: ['friends', 'address', 'shorthand'], ...WIKT('gng') },
  { category: 'teen', term: 'vro', emoji: '😤', ageGroup: 'middle', difficulty: 'medium', related: ['texting'], definition: 'Deliberately misspelled “bro.” Same energy, sillier spelling. Also “crodie” in the same family.', example: '“vro is NOT cooking with this fit.”', tags: ['address', 'spelling'], ...WIKT('vro') },
  { category: 'teen', term: 'crodie', emoji: '🐊', ageGroup: 'high_school', difficulty: 'hard', definition: '“Bro/homie,” from Crip-adjacent replacement of B with C — now meme-ified general slang detached from gang meaning.', example: '“my crodie since day one.”', tags: ['address', 'meme'], ...WIKT('crodie') },
  { category: 'teen', term: 'icl', emoji: '😮‍💨', ageGroup: 'high_school', difficulty: 'medium', related: ['texting'], definition: '“I can’t lie” — the UK-flavored tbh/ngl. Often opens a confession.', example: '“icl that movie kinda flopped.”', tags: ['acronym', 'honesty'], ...WIKT('icl') },
  { category: 'teen', term: 'caught lacking', emoji: '📸', ageGroup: 'high_school', difficulty: 'medium', related: ['gaming'], definition: 'Caught off-guard, unprepared, or embarrassed — from being caught without defense, now anything from a bad photo to an ambush in a game.', example: '“Camera caught him lacking mid-yawn.”', tags: ['embarrassment'], ...WIKT('caught lacking') },
  { category: 'teen', term: 'hawk tuah', emoji: '🦅', ageGroup: 'college', difficulty: 'hard', definition: 'The 2024 viral meme from a street interview — an onomatopoeia for spitting, with an explicit original context parents should know about. Became a general-purpose meme/soundbite.', example: 'Kids yell it as a random meme reference.', tags: ['meme', 'parent-aware', 'viral'], ...WIKT('hawk tuah') },
  { category: 'teen', term: 'what the sigma', emoji: '❓', ageGroup: 'middle', difficulty: 'medium', definition: '“What the heck” filtered through sigma-brainrot. Pure nonsense filler from the skibidi family.', example: 'Kid drops a pencil: “what the sigma?”', tags: ['brainrot', 'filler'], ...WIKT('what the sigma') },
  { category: 'teen', term: 'goblin mode', emoji: '👺', ageGroup: 'college', difficulty: 'easy', definition: 'Unapologetically lazy, messy, self-indulgent behavior — Oxford’s 2022 Word of the Year, still in rotation for rot-day energy.', example: '“Full goblin mode this weekend: snacks, blanket, zero pants.”', tags: ['word-of-the-year', 'rest'], ...WIKT('goblin mode') },
  { category: 'teen', term: 'Italian brainrot', emoji: '🇮🇹', ageGroup: 'elementary', difficulty: 'hard', definition: 'The 2025 wave of absurd AI-generated characters with pseudo-Italian names (Tralalero Tralala, Ballerina Cappuccina, Bombardiro Crocodilo). Younger kids recite the lore endlessly.', example: 'Your 8-year-old chanting “tralalero tralala” — this is why.', tags: ['brainrot', 'ai', 'gen-alpha', 'meme'], ...WIKI('Italian brainrot', 'Italian_brainrot') },

  // ============ 🎮 GAMING — competitive culture & Twitch language ============
  { category: 'gaming', term: 'goated', emoji: '🐐', difficulty: 'easy', related: ['teen', 'texting'], definition: 'GOAT as an adjective — elite, the best. “Goated with the sauce” for emphasis.', example: '“That update is goated.”', tags: ['praise'], ...WIKT('goated') },
  { category: 'gaming', term: 'cracked', emoji: '⚡', difficulty: 'medium', related: ['teen'], definition: 'Insanely skilled. A cracked player hits every shot.', example: '“The kid we matched with was cracked out of his mind.”', tags: ['praise', 'skill'], ...WIKT('cracked') },
  { category: 'gaming', term: 'washed', emoji: '🫧', difficulty: 'medium', related: ['teen'], definition: 'Past your prime; formerly good. Applies to players, athletes, and anyone over 25 according to teenagers.', example: '“He used to be a demon at this game. Washed now.”', tags: ['teasing', 'decline'], ...WIKT('washed') },
  { category: 'gaming', term: 'diff', emoji: '📊', difficulty: 'hard', definition: 'Short for “difference” — declaring a skill gap decided the game. “Jungle diff” = their jungler was better. Merciless in defeat.', example: '“That wasn’t a close match, that was a skill diff.”', tags: ['competitive', 'trash-talk'], ...WIKT('diff') },
  { category: 'gaming', term: 'carry', emoji: '🎒', difficulty: 'easy', related: ['teen', 'corporate'], definition: 'To single-handedly win for your team — you “carried” them. Also the person who did it. Used everywhere now (“she carried the group project”).', example: '“I went 20-2. Hard carry.”', tags: ['competitive', 'praise'], ...WIKT('carry') },
  { category: 'gaming', term: 'boosted', emoji: '🎈', difficulty: 'hard', definition: 'At a rank you didn’t earn — carried there by better players. An accusation, not a compliment.', example: '“No way he’s Diamond. Boosted.”', tags: ['competitive', 'accusation'], ...WIKT('boosted') },
  { category: 'gaming', term: 'hardstuck', emoji: '🧱', difficulty: 'hard', definition: 'Permanently stuck at a rank despite grinding. “Hardstuck Gold” is an identity and an insult.', example: '“Three seasons hardstuck Plat.”', tags: ['competitive', 'rank'], ...WIKT('hardstuck') },
  { category: 'gaming', term: 'Elo hell', emoji: '🔥', difficulty: 'hard', definition: 'The theory that low ranks trap good players because teammates are too chaotic to climb out. Debated forever; blamed always.', example: '“I’m not bad, I’m in Elo hell.”', tags: ['competitive', 'excuse'], ...WIKT('Elo hell') },
  { category: 'gaming', term: 'tilted', emoji: '😡', difficulty: 'medium', related: ['teen'], definition: 'Playing worse because you’re frustrated — the anger spiral. From poker. “Tilt queue” = queuing again while mad (never works).', example: '“I’m tilted, one more game.” (Famous last words.)', tags: ['emotion', 'poker-origin'], ...WIKT('tilted') },
  { category: 'gaming', term: 'throwing', emoji: '🗑️', difficulty: 'medium', related: ['teen'], definition: 'Losing a game you were winning — “we threw a 20-point lead.” Also intentionally playing badly.', example: '“We had the win and threw it.”', tags: ['competitive', 'failure'], ...WIKT('throwing') },
  { category: 'gaming', term: 'inting', emoji: '💀', difficulty: 'hard', definition: '“Intentionally feeding” — deliberately dying to ruin the game, or (jokingly) just playing terribly.', example: '“He’s 0-11. Either inting or having the worst day.”', tags: ['toxicity', 'moba'], ...WIKT('inting') },
  { category: 'gaming', term: 'feeding', emoji: '🍽️', difficulty: 'medium', definition: 'Dying repeatedly to the enemy, making them stronger. The cardinal team-game sin.', example: '“Stop feeding their sniper!”', tags: ['moba', 'failure'], ...WIKT('feeding') },
  { category: 'gaming', term: 'copium', emoji: '🚬', difficulty: 'medium', related: ['teen', 'texting'], definition: 'Cope + opium — the imaginary drug you’re “on” when refusing to accept a loss or bad news. Twitch-meme chemistry; sibling of hopium (irrational hope).', example: '“He says the sequel will fix everything. Pure copium.”', tags: ['twitch', 'meme', 'denial'], ...WIKT('copium') },
  { category: 'gaming', term: 'hopium', emoji: '🌈', difficulty: 'medium', definition: 'Irrational optimism, inhaled like a drug. The bull-market cousin of copium.', example: '“Full hopium that my team makes playoffs.”', tags: ['twitch', 'meme'], ...WIKT('hopium') },
  { category: 'gaming', term: 'malding', emoji: '👨‍🦲', difficulty: 'hard', definition: 'Mad + balding — so angry you’re losing hair. Twitch chat’s favorite way to mock a raging streamer.', example: '“Chat spamming MALDING as he loses again.”', tags: ['twitch', 'teasing'], ...WIKT('malding') },
  { category: 'gaming', term: 'sadge', emoji: '😔', difficulty: 'hard', related: ['texting'], definition: 'Sad, via the Twitch emote “Sadge.” Ironic-flavored sadness in chat speak.', example: '“Stream’s over. Sadge.”', tags: ['twitch', 'emote'], ...WIKT('sadge') },
  { category: 'gaming', term: 'KEKW', emoji: '🤣', difficulty: 'hard', definition: 'Twitch-chat laughter — the KEKW emote (a laughing man’s face). “KEK” is WoW-era “LOL.” Spammed when a streamer fails.', example: 'Chat floods KEKW as the speedrun dies.', tags: ['twitch', 'emote'], ...WIKI('Twitch emote culture', 'Twitch_(service)') },
  { category: 'gaming', term: 'built different', emoji: '🗿', difficulty: 'medium', related: ['teen'], definition: 'On another level — succeeding where everyone else fails, implying you’re constructed from superior parts. Sincere or ironic.', example: '“Turned in the essay early AND aced it. Built different.”', tags: ['praise', 'meme'], ...WIKT('built different') },

  // ============ 💻 CODING — the AI era ============
  { category: 'coding', term: 'vibe coding', emoji: '✨', difficulty: 'medium', related: ['corporate'], definition: 'Building software by describing what you want to an AI and accepting what it writes — coding on vibes, not review. Coined by Karpathy (2025); powerful, controversial, occasionally catastrophic.', example: '“The whole app was vibe coded in a weekend.”', tags: ['ai', 'trend'], ...WIKT('vibe coding') },
  { category: 'coding', term: 'hallucination', emoji: '👻', difficulty: 'medium', related: ['teen'], definition: 'When an AI confidently invents facts, citations, or APIs that don’t exist. The core failure mode everyone building with AI must handle.', example: '“The chatbot cited a court case that doesn’t exist. Classic hallucination.”', tags: ['ai', 'failure-mode'], ...WIKT('hallucination') },
  { category: 'coding', term: 'prompt engineering', emoji: '🪄', difficulty: 'medium', related: ['corporate'], definition: 'Crafting inputs to get better outputs from AI models — part skill, part folklore, briefly a job title.', example: '“Adding ‘think step by step’ is prompt engineering 101.”', tags: ['ai', 'skill'], ...WIKT('prompt engineering') },
  { category: 'coding', term: 'token', emoji: '🧩', difficulty: 'hard', definition: 'The word-chunks AI models read and write — and the unit you pay for. “Context window” = how many tokens a model can hold at once.', example: '“That long doc blew past the token limit.”', tags: ['ai', 'technical'], ...WIKT('token') },
  { category: 'coding', term: 'agentic', emoji: '🕹️', difficulty: 'hard', related: ['corporate'], definition: 'AI that takes multi-step actions on its own (browsing, running code, booking things) rather than just answering. 2025’s biggest buzzword.', example: '“The agentic workflow files the ticket and emails the customer itself.”', tags: ['ai', 'buzzword'], ...WIKT('agentic') },
  { category: 'coding', term: 'AI slop', emoji: '🥣', difficulty: 'easy', related: ['teen', 'corporate'], definition: 'Low-quality AI-generated content flooding the internet — spam articles, fake images, filler videos. The sibling of the teen glossary’s “slop.”', example: '“Search results are half AI slop now.”', tags: ['ai', 'quality'], ...WIKT('AI slop') },
  { category: 'coding', term: 'tech bro', emoji: '🧢', difficulty: 'easy', related: ['corporate', 'teen'], definition: 'The stereotype: patagonia vest, disruption talk, unearned confidence. Affectionate or scathing by context.', example: '“He explained my own job to me. Total tech bro.”', tags: ['archetype', 'culture'], ...WIKT('tech bro') },
  { category: 'coding', term: 'brogrammer', emoji: '💪', difficulty: 'medium', definition: 'Frat-culture programmer stereotype — the gym-and-code guy. Slightly dated but still deployed.', example: '“The startup’s all brogrammers and kombucha.”', tags: ['archetype'], ...WIKT('brogrammer') },
  { category: 'coding', term: 'crunch', emoji: '⏰', difficulty: 'medium', related: ['gaming', 'corporate'], definition: 'Mandatory overtime death-marches before a deadline — notorious in game studios. “Crunch culture” is the criticism.', example: '“The studio crunched for six months before launch.”', tags: ['work-culture', 'gaming-industry'], ...WIKT('crunch') },
  { category: 'coding', term: 'WFH / RTO', emoji: '🏠', difficulty: 'easy', related: ['corporate', 'texting'], definition: 'Work from home / return to office — the acronym battlefield of post-2020 work. RTO mandates are the villain in half of LinkedIn.', example: '“Three-day RTO killed my WFH setup.”', tags: ['acronym', 'work-culture'], ...WIKT('WFH') },
  { category: 'coding', term: 'async', emoji: '📬', difficulty: 'medium', related: ['corporate'], definition: 'Communication that doesn’t need everyone present — docs and messages instead of meetings. “Let’s handle it async” = please no meeting.', example: '“Remote teams live async.”', tags: ['work-culture', 'technical'], ...WIKT('async') },

  // ============ 🏢 CORPORATE — workplace-trend wave ============
  { category: 'corporate', term: 'quiet quitting', emoji: '🤫', difficulty: 'easy', related: ['teen'], definition: 'Doing exactly your job and nothing more — no hustle, no unpaid extra. Not actually quitting; the 2022 phrase that named a generation’s boundary-setting.', example: '“He stopped answering emails at 5:01. Quiet quitting.”', tags: ['work-culture', 'boundaries'], ...WIKT('quiet quitting') },
  { category: 'corporate', term: 'quiet firing', emoji: '🥶', difficulty: 'medium', definition: 'Management making a job so unpleasant (no raises, bad shifts, exclusion) that the employee quits “voluntarily.” The employer mirror of quiet quitting.', example: '“Moved off every project — that’s quiet firing.”', tags: ['work-culture', 'management'], ...WIKT('quiet firing') },
  { category: 'corporate', term: 'overemployed', emoji: '🎭', difficulty: 'medium', definition: 'Secretly working two (or more) full-time remote jobs at once. A whole subreddit-driven movement.', example: '“Two laptops, two standups, twice the salary.”', tags: ['remote', 'controversial'], ...WIKT('overemployed') },
  { category: 'corporate', term: 'ghost jobs', emoji: '👻', difficulty: 'medium', definition: 'Job postings for roles companies never intend to fill — posted to look growing, harvest resumes, or pacify overworked staff.', example: '“That listing has been up for 8 months. Ghost job.”', tags: ['hiring', 'deception'], ...WIKT('ghost job') },
  { category: 'corporate', term: 'dry promotion', emoji: '🏜️', difficulty: 'medium', definition: 'More title and responsibility, zero extra pay.', example: '“Congrats on ‘Senior’! Same paycheck though.”', tags: ['compensation'], ...WIKT('dry promotion') },
  { category: 'corporate', term: 'girlboss', emoji: '💼', difficulty: 'easy', related: ['teen'], definition: 'A woman crushing it in business — sincere in 2015, almost entirely ironic now (“gaslight, gatekeep, girlboss”).', example: '“She girlbossed a little too close to the sun.”', tags: ['archetype', 'ironic'], ...WIKT('girlboss') },
  { category: 'corporate', term: 'mouse jiggler', emoji: '🖱️', difficulty: 'medium', definition: 'A device/app that fakes activity so your status stays green while you step away. Companies now scan for them; people have been fired.', example: '“The audit found 12 mouse jigglers in accounting.”', tags: ['remote', 'surveillance'], ...WIKT('mouse jiggler') },
  { category: 'corporate', term: 'workation / bleisure', emoji: '🏖️', difficulty: 'easy', definition: 'Working remotely from a vacation spot (workation) or tacking leisure onto business travel (bleisure). The remote-era travel portmanteaus.', example: '“Two weeks in Lisbon, laptop in the mornings.”', tags: ['remote', 'travel'], ...WIKT('workation') },
  { category: 'corporate', term: 'lazy girl job', emoji: '💅', difficulty: 'medium', related: ['teen'], definition: 'A chill, decently-paid, low-stress job (often remote) that funds your actual life — a 2023 TikTok trend reframing ambition.', example: '“Remote coordinator role, no overtime — total lazy girl job.”', tags: ['tiktok', 'work-culture'], ...WIKI('Lazy girl job', 'Lazy_girl_job') },
];
