// Pack expansion v9 — full ingestion of the three remaining Bark/Axis guides:
//   • Bark Gaming Terms glossary (fetched 2026-09-07)
//   • Axis Parent's Guide to Emoji (fetched 2026-09-07)
//   • Axis Teen Slang, Back-to-School Edition Fall 2026 (fetched 2026-09-07)
// Definitions paraphrase those guides. No invented meanings.

const BARKG = {
  sourceName: 'Bark — Gaming Terms & Slang Glossary (2026)',
  sourceUrl: 'https://www.bark.us/blog/gaming-terms/',
};
const AXEMO = {
  sourceName: 'Axis — A Parent\u2019s Guide to Emoji (2026)',
  sourceUrl: 'https://axis.org/resource/a-parent-guide-to-emoji/',
};
const AXB2S = {
  sourceName: 'Axis — Teen Slang, Back-to-School Edition (Fall 2026)',
  sourceUrl: 'https://axis.org/resource/a-parents-guide-to-teen-slang-back-to-school-edition/',
};

export const PACK_TERMS_V9 = [
  // ============ 🎮 GAMING — Bark gaming glossary gaps ============
  { category: 'gaming', term: 'avatar', emoji: '🧍', difficulty: 'easy', definition: 'Your character\u2019s appearance in a game — customizable with features, clothes, and props. The gaming ancestor of the Bitmoji.', example: '“Spent an hour on my avatar before playing a minute.”', tags: ['identity'], ...BARKG },
  { category: 'gaming', term: 'crafting', emoji: '🛠️', difficulty: 'easy', definition: 'Building virtual items from collected materials — cloth + alcohol = first-aid kit. The core loop of Minecraft, Fortnite, and survival games.', example: '“Need more wood to craft the shelter.”', tags: ['mechanics'], ...BARKG },
  { category: 'gaming', term: 'GG EZ', emoji: '😏', difficulty: 'medium', related: ['texting'], definition: '“Good game, easy” — the trash-talk version of GG, snarkily implying your opponent was no challenge. Some games auto-censor it.', example: 'Typing “gg ez” after a close match is maximum disrespect.', tags: ['taunt', 'etiquette'], ...BARKG },
  { category: 'gaming', term: 'glitching', emoji: '🌀', difficulty: 'easy', definition: 'Exploiting a bug for unfair advantage — walking through walls, duplicating items. Distinct from lag: glitching is deliberate.', example: '“He glitched under the map so no one could hit him.”', tags: ['cheating', 'bugs'], ...BARKG },
  { category: 'gaming', term: 'killstreak', emoji: '🔥', difficulty: 'easy', definition: 'Consecutive kills without dying — many shooters award bonuses at milestones, which is why your kid can\u2019t pause right now.', example: '“Don\u2019t talk to me, I\u2019m on a 12 killstreak.”', tags: ['fps', 'mechanics'], ...BARKG },
  { category: 'gaming', term: 'MMORPG', emoji: '🌐', difficulty: 'medium', definition: 'Massively multiplayer online role-playing game — persistent fantasy/sci-fi worlds with thousands of players (World of Warcraft is the classic).', example: '“He\u2019s been in the same MMORPG guild since middle school.”', tags: ['acronym', 'genre'], ...BARKG },
  { category: 'gaming', term: 'mod', emoji: '🔧', difficulty: 'easy', related: ['coding'], definition: 'A player-made modification to a game — new features, characters, or rules. Modding is many kids\u2019 first taste of programming.', example: '“The Minecraft mod adds 200 new creatures.”', tags: ['customization', 'community'], ...BARKG },
  { category: 'gaming', term: 'squeaker', emoji: '🐭', difficulty: 'medium', definition: 'Insult for younger gamers whose voices haven\u2019t dropped yet — the high-pitched kid in voice chat. Often your kid, sometimes affectionately.', example: '“Lobby\u2019s full of squeakers tonight.”', tags: ['teasing', 'voice-chat'], ...BARKG },
  { category: 'gaming', term: 'you a bot', emoji: '🤖', difficulty: 'easy', related: ['teen'], definition: '“You\u2019re playing like a computer NPC” — bad, predictable, brainless. The gaming insult that escaped into school hallways.', example: '“Missed an open shot? You a bot.”', tags: ['insult'], ...BARKG },
  { category: 'gaming', term: 'loot boxes', emoji: '📦', difficulty: 'medium', related: ['safety'], definition: 'Paid randomized rewards — real money for a chance at rare skins/items. Widely criticized as gambling-adjacent for kids; some countries regulate them.', example: '“He spent $40 on loot boxes and got nothing good.”', tags: ['monetization', 'parent-alert', 'gambling'], ...BARKG },

  // ============ 🙂 EMOJI — Axis emoji guide (faces & tone) ============
  { category: 'emoji', term: 'grinning face 😃', emoji: '😃', difficulty: 'medium', related: ['texting'], definition: 'Per Axis: often sarcastic — a too-wide smile masking displeasure, like the single-tear emoji. Context: “Great, another group project 😃”.', example: '“Monday again 😃”', tags: ['sarcasm', 'tone'], ...AXEMO },
  { category: 'emoji', term: 'loudly crying 😭', emoji: '😭', difficulty: 'easy', related: ['teen', 'texting'], definition: 'Usually NOT sad — something was so funny (or shocking) it brought tears. The laughing emoji of Gen Z/Alpha, alongside 💀.', example: '“the way he tripped 😭😭”', tags: ['humor', 'reaction'], ...AXEMO },
  { category: 'emoji', term: 'pleading face 🥺', emoji: '🥺', difficulty: 'easy', related: ['teen'], definition: 'Soft sadness, vulnerability, or begging — often paired with 👉👈. “Can we get McDonald\u2019s 🥺”.', example: '“you\u2019re coming to my game right 🥺”', tags: ['emotion', 'begging'], ...AXEMO },
  { category: 'emoji', term: 'single tear 🥲', emoji: '🥲', difficulty: 'medium', definition: 'Smiling through despair — things are hanging by a thread but we\u2019re laughing about it. “Said \u2018love you\u2019 to my teacher 🥲”.', example: '“passed with a 70 exactly 🥲”', tags: ['humor', 'despair'], ...AXEMO },
  { category: 'emoji', term: 'melting face 🫠', emoji: '🫠', difficulty: 'medium', definition: 'Overwhelmed, dread, dissolving under pressure — the burnout emoji.', example: '“three tests tomorrow 🫠”', tags: ['stress', 'emotion'], ...AXEMO },
  { category: 'emoji', term: 'saluting face 🫡', emoji: '🫡', difficulty: 'easy', related: ['texting'], definition: 'Respectful agreement — “yes sir/ma\u2019am,” mission accepted. Sincere or playfully formal.', example: '“Take out the trash.” “🫡”', tags: ['agreement', 'respect'], ...AXEMO },
  { category: 'emoji', term: 'peeking eye 🫣', emoji: '🫣', difficulty: 'medium', definition: 'Hiding after saying something bold or confessing — softens the message. “I forgot to defrost the chicken 🫣”.', example: '“I may have broken the lamp 🫣”', tags: ['confession', 'softener'], ...AXEMO },
  { category: 'emoji', term: 'raised eyebrow 🤨', emoji: '🤨', difficulty: 'easy', definition: 'Suspicion — “explain yourself.” The digital side-eye.', example: '“You were WHERE at midnight 🤨”', tags: ['suspicion', 'reaction'], ...AXEMO },
  { category: 'emoji', term: 'zany face 🤪', emoji: '🤪', difficulty: 'medium', definition: 'Per Axis: silliness that lightens something disappointing — “Got an F on my final 🤪”. Coping, not just goofing.', example: '“lost my retainer again 🤪”', tags: ['humor', 'coping'], ...AXEMO },
  { category: 'emoji', term: 'cowboy face 🤠', emoji: '🤠', difficulty: 'hard', definition: 'Smiling through the pain — yee-haw on the outside, crisis on the inside. Same coping family as 🤪.', example: '“hosting both sides of the family this year 🤠”', tags: ['humor', 'coping'], ...AXEMO },
  { category: 'emoji', term: 'hand over mouth 🤭', emoji: '🤭', difficulty: 'easy', definition: 'Giddy excitement or delighted gossip — the “oooooh” emoji.', example: '“wait till you hear this 🤭”', tags: ['excitement', 'gossip'], ...AXEMO },
  { category: 'emoji', term: 'face in clouds 😶‍🌫️', emoji: '😶‍🌫️', difficulty: 'medium', definition: 'Head in the clouds, zoned out, mentally elsewhere — or deliberately oblivious.', example: '“me during 4th period 😶‍🌫️”', tags: ['mood'], ...AXEMO },
  { category: 'emoji', term: 'no mouth 😶', emoji: '😶', difficulty: 'easy', definition: 'At a loss for words — speechless, awkward silence.', example: '“she read the texts out loud 😶”', tags: ['reaction'], ...AXEMO },
  { category: 'emoji', term: 'astonished 😳', emoji: '😳', difficulty: 'easy', definition: 'Shock or judgment — the flushed wide-eyed stare.', example: '“you said that to the TEACHER 😳”', tags: ['reaction', 'judgment'], ...AXEMO },
  { category: 'emoji', term: 'relieved face 😌', emoji: '😌', difficulty: 'medium', definition: 'Contained excitement, staged nonchalance — pretending to be chill about something great.', example: '“just got asked to homecoming 😌”', tags: ['nonchalance'], ...AXEMO },

  // ---- Axis emoji: gestures & objects ----
  { category: 'emoji', term: 'thumbs up 👍', emoji: '👍', difficulty: 'medium', related: ['texting', 'corporate'], definition: 'Per Axis: reads as outdated, sarcastic, or passive-aggressive to teens — “Thanks for ruining the surprise 👍”. Parents mean it sincerely; kids receive it cold. A genuine generational divider.', example: 'A bare 👍 reply can end a group chat conversation.', tags: ['passive-aggressive', 'generational'], ...AXEMO },
  { category: 'emoji', term: 'nails 💅', emoji: '💅', difficulty: 'medium', related: ['teen'], definition: 'Sassy affirmation, unbothered energy, “and that\u2019s that.” Axis notes a negative use: insinuating a guy is being fruity.', example: '“Told him no and went back to my show 💅”', tags: ['sass', 'dual-meaning'], ...AXEMO },
  { category: 'emoji', term: 'lip bite 🫦', emoji: '🫦', difficulty: 'medium', related: ['safety'], definition: 'Flirting — usually sarcastic/ironic per Axis (“love when he wears cargo shorts 🫦”), but genuinely suggestive in DMs. Context matters.', example: 'Ironic thirst in comments; real thirst in DMs.', tags: ['flirting', 'dual-meaning'], ...AXEMO },
  { category: 'emoji', term: 'pregnant woman 🤰', emoji: '🤰', difficulty: 'hard', related: ['teen'], definition: 'Someone is so attractive that just looking at them “got me pregnant.” Hyperbolic thirst compliment.', example: 'Under a celebrity post: “🤰🤰🤰”', tags: ['humor', 'attraction'], ...AXEMO },
  { category: 'emoji', term: 'man with cane 👨‍🦯', emoji: '👨‍🦯', difficulty: 'hard', definition: 'Per Axis: going in blind — knowingly making a bad decision while ignoring the red flags.', example: '“texting my ex again 👨‍🦯”', tags: ['humor', 'self-aware'], ...AXEMO },
  { category: 'emoji', term: 'kneeling 🧎', emoji: '🧎', difficulty: 'hard', definition: 'Desperate pleading — on knees, begging. “DROP THE ALBUM 🧎”.', example: '“extend the deadline 🧎🧎”', tags: ['begging', 'humor'], ...AXEMO },
  { category: 'emoji', term: 'see-no-evil 🙈', emoji: '🙈', difficulty: 'easy', definition: 'Shyness or playful embarrassment.', example: '“he liked my post from 2022 🙈”', tags: ['shy', 'flirting'], ...AXEMO },
  { category: 'emoji', term: 'sparkles ✨', emoji: '✨', difficulty: 'easy', related: ['teen'], definition: 'Mood-lightener and ironic emphasis — “spilled coffee on my white pants ✨”. Also decorates genuinely aesthetic things. (See fairy sparkles 🧚✨ for the mean version.)', example: '“failing ✨ gracefully ✨”', tags: ['irony', 'aesthetic'], ...AXEMO },
  { category: 'emoji', term: 'heart hands 🫶', emoji: '🫶', difficulty: 'easy', definition: 'Love/support — the young replacement for a plain ❤️.', example: '“proud of you 🫶”', tags: ['affection'], ...AXEMO },
  { category: 'emoji', term: 'folded hands 🙏', emoji: '🙏', difficulty: 'easy', definition: 'Thank you, please, or gratitude. (Prayer or high-five depending on who you ask — teens mean thanks.)', example: '“ride home? 🙏”', tags: ['gratitude'], ...AXEMO },
  { category: 'emoji', term: 'bullseye 🎯', emoji: '🎯', difficulty: 'easy', related: ['texting'], definition: 'Dead-on accurate — “exactly right.”', example: 'Reply to a hot take that nails it: 🎯', tags: ['agreement'], ...AXEMO },
  { category: 'emoji', term: 'charts 📈📉', emoji: '📈', difficulty: 'easy', related: ['corporate'], definition: 'Things going well (📈) or badly (📉) — applied to anything: grades, vibes, friendships, aura.', example: '“my sleep schedule 📉 my caffeine intake 📈”', tags: ['status', 'humor'], ...AXEMO },
  { category: 'emoji', term: 'squirt gun 🔫', emoji: '🔫', difficulty: 'medium', definition: 'Comic frustration — “I\u2019m upset about this” with a toy-gun punchline (the emoji replaced the realistic pistol years ago). Same job as 🔪: humor, not threat. Genuine threats read very differently in context.', example: '“Chick-fil-A closed on Sunday 🔫”', tags: ['humor', 'frustration'], ...AXEMO },
  { category: 'emoji', term: 'knife 🔪', emoji: '🔪', difficulty: 'medium', definition: 'Humorous outrage — dramatic “I could kill” energy about minor grievances. As with 🔫, context separates joke from genuine concern.', example: '“he spoiled the finale 🔪”', tags: ['humor', 'frustration'], ...AXEMO },
  { category: 'emoji', term: 'red heart ❤️', emoji: '❤️', difficulty: 'easy', definition: 'Love — and, per Axis, a softener for rejection (“I can\u2019t come ❤️”). The heart-color hierarchy is its own teen politics.', example: '“sorry can\u2019t make it ❤️” = gentle no.', tags: ['affection', 'dual-meaning'], ...AXEMO },

  // ============ 🧃 TEEN — Axis Back-to-School Fall 2026 ============
  { category: 'teen', term: 'addy', emoji: '📍', ageGroup: 'high_school', difficulty: 'medium', related: ['texting', 'safety'], definition: 'Address — “send the addy.” (Older drug slang used it for Adderall; today\u2019s teens mostly mean location. Context check.)', example: '“Mom can drop me — what\u2019s the addy?”', tags: ['shorthand', 'dual-meaning'], ...AXB2S },
  { category: 'teen', term: 'almond mom', emoji: '🥛', ageGroup: 'high_school', difficulty: 'medium', definition: 'A mom with restrictive diet-culture habits who pushes them on her kids (“just eat a few almonds”). Opposite: butter mom, who promotes moderate, normal eating.', example: '“My almond mom banned seed oils.”', tags: ['archetype', 'diet-culture', 'parent-aware'], ...AXB2S },
  { category: 'teen', term: 'body tea', emoji: '☕', ageGroup: 'high_school', difficulty: 'hard', definition: 'A compliment on someone\u2019s body/figure. From “tea” = the goods.', example: '“Did you see her prom dress? Body tea.”', tags: ['compliment', 'body'], ...AXB2S },
  { category: 'teen', term: 'call yo Uber', emoji: '🚗', ageGroup: 'high_school', difficulty: 'medium', definition: '“Get out of here” — dismissing someone who\u2019s annoyed you, as if summoning their ride home.', example: '“You did NOT just say that. Call yo Uber.”', tags: ['dismissal', 'humor'], ...AXB2S },
  { category: 'teen', term: 'caucasity', emoji: '😬', ageGroup: 'high_school', difficulty: 'hard', definition: 'Caucasian + audacity — behavior displaying white privilege/obliviousness. Pointed humor.', example: '“Shoes on in the house? The caucasity.”', tags: ['callout', 'humor'], ...AXB2S },
  { category: 'teen', term: 'choose violence', emoji: '⚔️', ageGroup: 'high_school', difficulty: 'medium', definition: 'To say/do something deliberately provocative as a joke — “woke up and chose violence.”', example: '“He put the cast iron in the dishwasher. Chose violence.”', tags: ['humor', 'provocation'], ...AXB2S },
  { category: 'teen', term: 'chud', emoji: '🕳️', ageGroup: 'college', difficulty: 'hard', definition: 'A loser. Started as a movie acronym (Cannibalistic Humanoid Underground Dweller), passed through politics, generalized to any basement-dweller insult.', example: '“Ignore the reply-guy chuds.”', tags: ['insult', 'internet'], ...AXB2S },
  { category: 'teen', term: 'clanker', emoji: '🦾', ageGroup: 'middle', difficulty: 'medium', related: ['coding'], definition: 'Insult for AI and robots — from Star Wars\u2019 droid slur. The kids\u2019 word for disrespecting chatbots.', example: '“Claude is a total clanker.” (Rude.)', tags: ['ai', 'insult', 'humor'], ...AXB2S },
  { category: 'teen', term: 'clipped', emoji: '📎', ageGroup: 'high_school', difficulty: 'medium', related: ['gaming'], definition: 'Three uses per Axis: killed off (gaming), exposed/caught in a bad moment (social), or photographed unready.', example: '“I clipped mom mid-yawn, look.”', tags: ['multi-meaning'], ...AXB2S },
  { category: 'teen', term: 'community dih / puh', emoji: '🚩', ageGroup: 'high_school', difficulty: 'hard', related: ['safety'], definition: 'Crude terms for a promiscuous guy (dih) or girl (puh) — “community property” implication. Slut-shaming language parents should recognize.', example: 'Heard in gossip; worth a values conversation.', tags: ['sexual', 'bullying', 'parent-aware'], ...AXB2S },
  { category: 'teen', term: 'flow state', emoji: '🌊', ageGroup: 'high_school', difficulty: 'easy', related: ['corporate'], definition: 'Deep immersion where everything clicks — borrowed from psychology, used for study sessions and games going perfectly.', example: '“Three hours of homework, full flow state.”', tags: ['focus', 'psychology'], ...AXB2S },
  { category: 'teen', term: 'frame mogged', emoji: '🖼️', ageGroup: 'high_school', difficulty: 'hard', definition: 'Out-shined in a photo — someone looked better than you in the same frame. From mogging.', example: '“My sister frame mogged me in the Christmas card.”', tags: ['-maxxing-family', 'photos'], ...AXB2S },
  { category: 'teen', term: 'G', emoji: '🤜', ageGroup: 'high_school', difficulty: 'easy', definition: 'Friend/buddy — “that\u2019s my G.” Old-school, still current.', example: '“Good looks, G.”', tags: ['address', 'classic'], ...AXB2S },
  { category: 'teen', term: 'granola', emoji: '🥾', ageGroup: 'high_school', difficulty: 'easy', definition: 'Crunchy-outdoorsy aesthetic — Birkenstocks, hiking, organic food, small-business energy.', example: '“New Birkenstocks. I look so granola.”', tags: ['aesthetic'], ...AXB2S },
  { category: 'teen', term: 'intrusive thoughts', emoji: '🧠', ageGroup: 'high_school', difficulty: 'medium', definition: 'Used (clinically incorrectly) for impulsive urges — “let the intrusive thoughts win” = got 2am Taco Bell. The real psychiatric term means unwanted distressing thoughts; kids mean whims.', example: '“Intrusive thoughts won: I bleached my hair.”', tags: ['psychology', 'misused', 'parent-aware'], ...AXB2S },
  { category: 'teen', term: 'LARPing', emoji: '🎭', ageGroup: 'college', difficulty: 'medium', related: ['gaming'], definition: 'Live-action role play — literally costumes in the park; figuratively, an insult for someone pretending to be what they aren\u2019t.', example: '“He\u2019s LARPing as a gym bro.”', tags: ['insult', 'pretending'], ...AXB2S },
  { category: 'teen', term: 'lowkenuinely', emoji: '🫱', ageGroup: 'high_school', difficulty: 'hard', related: ['texting'], definition: 'Low-key + genuinely — sincere but keeping it nonchalant. Peak hedge-word engineering.', example: '“I lowkenuinely prefer bingo night to parties.”', tags: ['portmanteau', 'hedge'], ...AXB2S },
  { category: 'teen', term: 'mad', emoji: '💢', ageGroup: 'high_school', difficulty: 'easy', definition: 'Intensifier — “very”: mad expensive, mad late. NY classic still in rotation.', example: '“New iPhone is mad expensive.”', tags: ['intensifier', 'regional'], ...AXB2S },
  { category: 'teen', term: '-maxxing', emoji: '📈', ageGroup: 'high_school', difficulty: 'medium', definition: 'Suffix for maximizing anything: proteinmaxxing, sleepmaxxing, gymmaxxing. Escaped from looksmaxxing into general self-improvement talk.', example: '“This semester I\u2019m sleepmaxxing.”', tags: ['suffix', '-maxxing-family'], ...AXB2S },
  { category: 'teen', term: 'moving in silence', emoji: '🤐', ageGroup: 'high_school', difficulty: 'medium', related: ['corporate'], definition: 'Keeping plans private until they succeed — announce the win, not the attempt.', example: '“Started training months ago. Moving in silence.”', tags: ['strategy', 'discipline'], ...AXB2S },
  { category: 'teen', term: 'overstimulated', emoji: '🌪️', ageGroup: 'middle', difficulty: 'easy', definition: 'Overwhelmed — sensory or emotional. Therapy-speak that went mainstream with teens.', example: '“Mall on a Saturday? Instantly overstimulated.”', tags: ['mental-health', 'therapy-speak'], ...AXB2S },
  { category: 'teen', term: 'paper', emoji: '💵', ageGroup: 'high_school', difficulty: 'easy', definition: 'Money. “Getting paper” = earning.', example: '“Summer job = paper for the car.”', tags: ['money', 'classic'], ...AXB2S },
  { category: 'teen', term: 'passenger princess', emoji: '👸', ageGroup: 'college', difficulty: 'easy', definition: 'Someone who always rides shotgun and never drives — affectionate teasing, mostly.', example: '“I don\u2019t drive; I\u2019m the passenger princess.”', tags: ['archetype', 'humor'], ...AXB2S },
  { category: 'teen', term: 'pleb', emoji: '🏛️', ageGroup: 'high_school', difficulty: 'medium', related: ['gaming'], definition: 'A commoner/lower-class person — derogatory, from Roman “plebeian.” Gaming and school-status teasing.', example: '“Only plebs buy the base skin.”', tags: ['insult', 'classical'], ...AXB2S },
  { category: 'teen', term: 'quiet on the creek', emoji: '🎣', ageGroup: 'high_school', difficulty: 'hard', definition: 'Keeping something on the down-low — deliberately fuzzy meaning, from a Saucy Santana song about not scaring the fish.', example: '“New relationship? Quiet on the creek for now.”', tags: ['secrecy', 'music'], ...AXB2S },
  { category: 'teen', term: 'ran through', emoji: '🚩', ageGroup: 'high_school', difficulty: 'medium', related: ['safety'], definition: 'Derogatory: sexually experienced with many partners. Slut-shaming term — flagged for parents in Axis\u2019s explicit-content list.', example: 'Gossip term worth addressing directly.', tags: ['sexual', 'bullying', 'parent-aware'], ...AXB2S },
  { category: 'teen', term: 'real', emoji: '💯', ageGroup: 'high_school', difficulty: 'easy', related: ['texting'], definition: 'Affirmation of authenticity — the one-word “I agree completely.”', example: '“I need this week to end.” “Real.”', tags: ['agreement'], ...AXB2S },
  { category: 'teen', term: 'recession indicator', emoji: '📉', ageGroup: 'college', difficulty: 'medium', related: ['corporate'], definition: 'Joke label for any small austerity — skipping Starbucks, shorter nails, rewearing outfits. Economic anxiety as meme.', example: '“No more DoorDash?” “Recession indicator.”', tags: ['money', 'meme'], ...AXB2S },
  { category: 'teen', term: 'reheated nachos', emoji: '🧀', ageGroup: 'high_school', difficulty: 'hard', definition: 'A worse version of something that was better the first time — sequels, trends, copycats.', example: '“That show\u2019s reboot is reheated nachos.”', tags: ['criticism', 'metaphor'], ...AXB2S },
  { category: 'teen', term: 'soft life', emoji: '🛁', ageGroup: 'college', difficulty: 'easy', definition: 'A lifestyle of ease and low stress as the goal — the anti-grind aspiration.', example: '“Finals done. Entering my soft life era.”', tags: ['lifestyle', 'rest'], ...AXB2S },
  { category: 'teen', term: 'you the birthday', emoji: '🎂', ageGroup: 'high_school', difficulty: 'hard', definition: 'Making yourself the center of attention — like it\u2019s your birthday — flattering or not.', example: '“Showed up in a suit to a picnic. You the birthday.”', tags: ['attention', 'teasing'], ...AXB2S },
  // ---- Radar catches from the first 7-source scan (2026-09-07) ----
  { category: 'safety', term: 'cart', emoji: '🖊️', difficulty: 'medium', related: ['teen'], definition: 'A cartridge for a vape pen — usually THC oil. “Carts” in a teen’s texts are rarely about shopping.', example: '“He’s selling carts” = THC cartridges.', tags: ['parent-alert', 'drugs', 'vaping'], sourceName: 'Bark — Drug Slang Emojis & Codes (2026)', sourceUrl: 'https://www.bark.us/blog/drug-slang-emojis/' },
  { category: 'safety', term: 'pen', emoji: '🖋️', difficulty: 'medium', related: ['teen'], definition: 'A vape pen — for nicotine or weed, cartridge-based. Looks like a USB drive or actual pen; easy to miss in a pencil case.', example: '“Hitting the pen” between classes.', tags: ['parent-alert', 'vaping', 'drugs'], sourceName: 'Bark — Drug Slang Emojis & Codes (2026)', sourceUrl: 'https://www.bark.us/blog/drug-slang-emojis/' },
  { category: 'safety', term: 'Special K', emoji: '🐴', difficulty: 'hard', definition: 'Ketamine — the dissociative anesthetic, not the cereal. Club-drug slang parents should recognize.', example: 'Cereal talk in a party context isn’t about breakfast.', tags: ['parent-alert', 'drugs'], sourceName: 'Bark — Drug Slang Emojis & Codes (2026)', sourceUrl: 'https://www.bark.us/blog/drug-slang-emojis/' },
  { category: 'safety', term: 'snow / yayo', emoji: '🌨️', difficulty: 'medium', definition: 'Cocaine — the two most common word-codes (alongside the ❄️ emoji family).', example: '“Snow” outside of weather talk deserves attention.', tags: ['parent-alert', 'drugs'], sourceName: 'Bark — Drug Slang Emojis & Codes (2026)', sourceUrl: 'https://www.bark.us/blog/drug-slang-emojis/' },
  { category: 'safety', term: 'clapping cheeks', emoji: '👏', difficulty: 'hard', definition: 'Having sex — current crude teen euphemism per Bark’s sexting guide.', example: 'Overheard in jokes; explicitly sexual.', tags: ['sexual', 'parent-alert'], sourceName: 'Bark — Sexual Slang & Sexting Codes (2026)', sourceUrl: 'https://www.bark.us/blog/sexual-slang/' },
  { category: 'safety', term: 'leg booty', emoji: '🏳️‍🌈', difficulty: 'hard', related: ['texting'], definition: 'Algospeak for “LGBTQ” — sounds it out to dodge moderation filters. Not derogatory in itself; context decides.', example: '“She’s leg booty” in filter-dodging posts.', tags: ['algospeak', 'lgbtq'], sourceName: 'Bark — Sexual Slang & Sexting Codes (2026)', sourceUrl: 'https://www.bark.us/blog/sexual-slang/' },
  { category: 'safety', term: 'nip nops', emoji: '🔞', difficulty: 'hard', definition: 'Algospeak for nipples — cutesy spelling to evade content filters.', example: 'Filter-dodging body talk.', tags: ['algospeak', 'sexual'], sourceName: 'Bark — Sexual Slang & Sexting Codes (2026)', sourceUrl: 'https://www.bark.us/blog/sexual-slang/' },
  { category: 'safety', term: 'spicy eggplant', emoji: '🌶️', difficulty: 'hard', definition: 'A vibrator, per Bark’s sexting-code list — food-emoji language taken one step further.', example: 'Appears in “spicy” shopping-haul contexts.', tags: ['sexual', 'algospeak'], sourceName: 'Bark — Sexual Slang & Sexting Codes (2026)', sourceUrl: 'https://www.bark.us/blog/sexual-slang/' },
  { category: 'safety', term: 'accountant', emoji: '🧾', difficulty: 'hard', related: ['corporate'], definition: 'Code for sex worker / OnlyFans creator — because nobody asks follow-up questions about a boring job. Parents seeing “accountant” jokes on TikTok now know.', example: '“She’s an accountant” wink-wink.', tags: ['sexual', 'code-word'], sourceName: 'Bark — Sexual Slang & Sexting Codes (2026)', sourceUrl: 'https://www.bark.us/blog/sexual-slang/' },
  { category: 'teen', term: 'butter mom', emoji: '🧈', ageGroup: 'high_school', difficulty: 'medium', definition: 'The opposite of an almond mom — promotes sensible, moderate, guilt-free eating.', example: '“We have whole milk. I have a butter mom.”', tags: ['archetype', 'diet-culture'], sourceName: 'Axis — Teen Slang, Back-to-School Edition (Fall 2026)', sourceUrl: 'https://axis.org/resource/a-parents-guide-to-teen-slang-back-to-school-edition/' },
  { category: 'teen', term: 'DL', emoji: '🤫', ageGroup: 'high_school', difficulty: 'easy', related: ['texting'], definition: '“Down low” — keep it secret. “Keep it on the DL.”', example: '“We’re dating, keep it on the DL.”', tags: ['secrecy', 'acronym'], sourceName: 'Axis — Teen Slang, Back-to-School Edition (Fall 2026)', sourceUrl: 'https://axis.org/resource/a-parents-guide-to-teen-slang-back-to-school-edition/' },
  // ---- From Bark's TikTok Slang guide (discovered by the new index scan, 2026-09-07) ----
  { category: 'teen', term: 'FYP', emoji: '📱', ageGroup: 'middle', difficulty: 'easy', related: ['texting'], definition: 'For You Page — TikTok\u2019s algorithmic home feed. \u201CMade it to the FYP\u201D = the algorithm blessed your video.', example: '\u201CThis dance is all over my FYP.\u201D', tags: ['acronym', 'tiktok'], sourceName: 'Bark — TikTok Slang Guide (2026)', sourceUrl: 'https://www.bark.us/blog/tiktok-slang/' },
  { category: 'teen', term: 'it\u2019s the ___ for me', emoji: '👉', ageGroup: 'high_school', difficulty: 'medium', definition: 'Fill-in-the-blank callout of the one detail that makes or breaks something: \u201Cit\u2019s the early mornings for me.\u201D Praise or roast.', example: '\u201CIt\u2019s the confidence for me.\u201D', tags: ['tiktok', 'template'], sourceName: 'Bark — TikTok Slang Guide (2026)', sourceUrl: 'https://www.bark.us/blog/tiktok-slang/' },
  { category: 'teen', term: 'say sike rn', emoji: '😧', ageGroup: 'middle', difficulty: 'medium', related: ['texting'], definition: '\u201CPlease tell me you\u2019re joking right now\u201D — the modern SIKE!, deployed at bad news.', example: '\u201CSchool on Saturday?? Say sike rn.\u201D', tags: ['tiktok', 'meme'], sourceName: 'Bark — TikTok Slang Guide (2026)', sourceUrl: 'https://www.bark.us/blog/tiktok-slang/' },
  { category: 'teen', term: 'it really do be like that', emoji: '🌊', ageGroup: 'high_school', difficulty: 'medium', definition: '\u201CIt is what it is\u201D — resigned, relatable acceptance of life\u2019s nonsense. Grammar intentionally loose.', example: '\u201CLost my headphones AND my keys.\u201D \u201CIt really do be like that sometimes.\u201D', tags: ['tiktok', 'acceptance'], sourceName: 'Bark — TikTok Slang Guide (2026)', sourceUrl: 'https://www.bark.us/blog/tiktok-slang/' },
  { category: 'emoji', term: 'credit card slam 💥💳💥', emoji: '💥', difficulty: 'medium', related: ['teen'], definition: 'The \u201Cshut up and take my money\u201D trend — banging a credit card on the table for something you\u2019d buy instantly. Comment-section spam: 💥💥💳💥💥.', example: 'Under a sneaker drop: 💥💥💳💥💥', tags: ['tiktok', 'hype'], sourceName: 'Bark — TikTok Slang Guide (2026)', sourceUrl: 'https://www.bark.us/blog/tiktok-slang/' },
  { category: 'safety', term: 'P ⭐ (porn star)', emoji: '⭐', difficulty: 'hard', definition: 'The letter P + star emoji = \u201Cporn star\u201D — filter-dodging code from TikTok. Same family as 🌽 and ⬛🟧.', example: 'In bios and comments where the word would be blocked.', tags: ['sexual', 'algospeak', 'parent-alert'], sourceName: 'Bark — TikTok Slang Guide (2026)', sourceUrl: 'https://www.bark.us/blog/tiktok-slang/' },
];
