// Pack expansion v6 — full Axis cross-reference import.
// Source: Axis — A Parent's Guide to Teen Slang (2026 edition), fetched 2026-08-15.
// Definitions paraphrase the Axis guide. No invented meanings.

const AXIS = {
  sourceName: 'Axis — A Parent\u2019s Guide to Teen Slang (2026)',
  sourceUrl: 'https://axis.org/resource/a-parent-guide-to-teen-slang/',
};

export const PACK_TERMS_V6 = [
  // ---- Safety-relevant Axis terms ----
  { category: 'safety', term: 'stealthing', emoji: '🚨', difficulty: 'hard', definition: 'Secretly removing a condom during sex without consent — a form of sexual assault. Axis includes it so parents know the word if it comes up.', example: 'A term from conversations about consent.', tags: ['parent-alert', 'sexual', 'consent'], ...AXIS },
  { category: 'safety', term: 'hooking up', emoji: '💋', difficulty: 'medium', related: ['teen'], definition: 'Deliberately vague — anything from kissing to sex. The ambiguity is the point; ask before assuming either extreme.', example: '“They hooked up at the party” could mean many things.', tags: ['sexual', 'ambiguous'], ...AXIS },
  { category: 'safety', term: 'bop', emoji: '🎵', difficulty: 'medium', related: ['teen'], definition: 'Two meanings: a catchy song (“this song is a bop”) — or, per Axis, a derogatory term for a promiscuous girl. Context is everything.', example: '“That track is a bop” vs. an insult — listen carefully.', tags: ['dual-meaning', 'bullying'], ...AXIS },
  { category: 'safety', term: '-ussy', emoji: '🔞', difficulty: 'hard', definition: 'A crude suffix (from a vulgar word) teens attach to anything for shock humor. Mostly absurdist joking, but explicitly sexual in origin.', example: 'Attached to random words for shock laughs.', tags: ['sexual', 'humor'], ...AXIS },

  // ---- Teen: relationships & social dynamics ----
  { category: 'teen', term: 'breadcrumbing', emoji: '🍞', ageGroup: 'college', difficulty: 'medium', definition: 'Doling out just enough attention to keep someone interested without ever committing. Romantic manipulation; Axis also logs the joke name “Hansel and Gretelling.”', example: '“He texts her once a week — pure breadcrumbing.”', tags: ['dating', 'manipulation'], ...AXIS },
  { category: 'teen', term: 'zombie', emoji: '🧟', ageGroup: 'college', difficulty: 'medium', definition: 'A romantic interest who ghosts you… then comes back from the dead months later like nothing happened.', example: '“He zombied me with a ‘hey stranger’ text.”', tags: ['dating'], ...AXIS },
  { category: 'teen', term: 'catch feels', emoji: '💘', ageGroup: 'high_school', difficulty: 'easy', definition: 'To develop romantic feelings, often unplanned and mildly unwelcome.', example: '“It was casual until someone caught feels.”', tags: ['dating'], ...AXIS },
  { category: 'teen', term: 'curve', emoji: '↩️', ageGroup: 'high_school', difficulty: 'medium', definition: 'To reject someone romantically — dodge their advance like a curve around an obstacle.', example: '“He asked for her number and got curved.”', tags: ['dating', 'rejection'], ...AXIS },
  { category: 'teen', term: 'pulling', emoji: '🧲', ageGroup: 'high_school', difficulty: 'medium', definition: 'Successfully attracting romantic attention. “Who did he pull?” = who did he get.', example: '“Did you see who she pulled for prom?”', tags: ['dating'], ...AXIS },
  { category: 'teen', term: 'boo', emoji: '💑', ageGroup: 'high_school', difficulty: 'easy', definition: 'Significant other. “Boo’d up” = happily coupled.', example: '“Movie night with my boo.”', tags: ['dating', 'classic'], ...AXIS },
  { category: 'teen', term: 'left on read', emoji: '📪', ageGroup: 'high_school', difficulty: 'easy', related: ['texting'], definition: 'They read your message and simply… did not reply. The read receipt makes it official.', example: '“Left on read for six hours. I’m unwell.”', tags: ['texting-culture', 'dating'], ...AXIS },
  { category: 'teen', term: 'ghosting', emoji: '🫗', ageGroup: 'high_school', difficulty: 'easy', related: ['texting'], definition: 'Cutting off all contact with zero explanation — vanishing from someone’s digital world.', example: '“Three great dates, then total ghosting.”', tags: ['dating', 'classic'], ...AXIS },
  { category: 'teen', term: 'fruity', emoji: '🍓', ageGroup: 'high_school', difficulty: 'medium', definition: 'Suggestive of being gay — often used playfully and, per Axis, “not always logically.”', example: '“Rain is fruity and I’m not explaining why.”', tags: ['lgbtq', 'humor'], ...AXIS },
  { category: 'teen', term: 'hunty', emoji: '💅', ageGroup: 'college', difficulty: 'hard', definition: 'From drag culture: honey + an insult, softened into a sassy term of endearment among friends.', example: '“Okay hunty, we see you.”', tags: ['drag-culture', 'address'], ...AXIS },

  // ---- Teen: reactions & expressions ----
  { category: 'teen', term: 'deadass', emoji: '😐', ageGroup: 'high_school', difficulty: 'medium', related: ['texting'], definition: 'Completely serious, no joke. NY-flavored “for real.”', example: '“I’m deadass, the test is tomorrow.”', tags: ['emphasis'], ...AXIS },
  { category: 'teen', term: 'oof', emoji: '😮‍💨', ageGroup: 'middle', difficulty: 'easy', related: ['texting'], definition: 'The sound of secondhand pain — what you say when there’s nothing to say.', example: '“I failed by one point.” “Oof.”', tags: ['reaction'], ...AXIS },
  { category: 'teen', term: 'say less', emoji: '🤝', ageGroup: 'high_school', difficulty: 'medium', definition: '“I’m fully on board — no more information needed.”', example: '“Ice cream and a movie?” “Say less.”', tags: ['agreement'], ...AXIS },
  { category: 'teen', term: 'sending me', emoji: '🚀', ageGroup: 'high_school', difficulty: 'medium', definition: 'Making you laugh uncontrollably — sending you over the edge.', example: '“This video is SENDING me.”', tags: ['humor', 'reaction'], ...AXIS },
  { category: 'teen', term: 'I fear', emoji: '😔', ageGroup: 'high_school', difficulty: 'medium', definition: 'A dramatic preface for blunt truth: “I fear that color isn’t working.”', example: '“I fear the group project is doomed.”', tags: ['dramatic', 'preface'], ...AXIS },
  { category: 'teen', term: 'pressed', emoji: '😾', ageGroup: 'high_school', difficulty: 'medium', definition: 'Upset, bothered, unable to let it go.', example: '“She’s still pressed about losing that game.”', tags: ['emotion'], ...AXIS },
  { category: 'teen', term: 'done', emoji: '🏳️', ageGroup: 'high_school', difficulty: 'easy', definition: 'Completely over it — a person, task, or situation. Emotional resignation as a full sentence.', example: '“I’m done with this whole week.”', tags: ['emotion'], ...AXIS },
  { category: 'teen', term: 'RIP me', emoji: '🪦', ageGroup: 'middle', difficulty: 'easy', related: ['texting'], definition: '“Rest in peace,” pronounced “rip” — comic despair over minor tragedy.', example: '“Forgot my charger. RIP me.”', tags: ['humor', 'despair'], ...AXIS },
  { category: 'teen', term: 'oop', emoji: '😶', ageGroup: 'middle', difficulty: 'easy', definition: 'Witnessing awkwardness — “and I oop.”', example: 'Already have this one? The radar will tell us.', tags: ['reaction'], ...AXIS },
  { category: 'teen', term: 'tweakin', emoji: '🤪', ageGroup: 'high_school', difficulty: 'medium', definition: 'Acting irrational or overreacting — behavior that doesn’t make sense. From drug-influenced behavior, now general.', example: '“Mom was tweakin about curfew.”', tags: ['behavior'], ...AXIS },
  { category: 'teen', term: 'wild / wildin’', emoji: '🤯', ageGroup: 'high_school', difficulty: 'easy', definition: 'Shocking, unbelievable — or, of a person, acting out of pocket.', example: '“You met Kendrick?? That’s wild.”', tags: ['reaction', 'classic'], ...AXIS },
  { category: 'teen', term: 'weird flex but ok', emoji: '🏋️', ageGroup: 'high_school', difficulty: 'medium', definition: 'Sarcastic response to a brag about something not worth bragging about.', example: '“I’ve never washed my car.” “Weird flex but ok.”', tags: ['sarcasm', 'meme'], ...AXIS },

  // ---- Teen: praise & performance ----
  { category: 'teen', term: 'blueprint', emoji: '📐', ageGroup: 'high_school', difficulty: 'medium', definition: 'The original that everyone else copies — so good it became the standard.', example: '“Every boy band is chasing One Direction. They’re the blueprint.”', tags: ['praise'], ...AXIS },
  { category: 'teen', term: 'serving', emoji: '🍾', ageGroup: 'high_school', difficulty: 'medium', definition: 'Looking exceptionally good — delivering excellence. Cousin of “ate.”', example: '“She’s serving in that jacket.”', tags: ['compliment', 'fashion'], ...AXIS },
  { category: 'teen', term: 'let them cook', emoji: '👨‍🍳', ageGroup: 'high_school', difficulty: 'medium', related: ['gaming'], definition: 'Don’t interrupt — they’re mid-brilliance and the result will be impressive. Past tense: “they cooked.”', example: '“Wait, let him cook, this idea is actually good.”', tags: ['praise', 'patience'], ...AXIS },
  { category: 'teen', term: 'go off', emoji: '📣', ageGroup: 'high_school', difficulty: 'medium', definition: 'Permission to rant — or ironic “sure, do your thing.”', example: '“He was so rude to you. Go off!”', tags: ['encouragement'], ...AXIS },
  { category: 'teen', term: 'keep it 100', emoji: '💯', ageGroup: 'high_school', difficulty: 'easy', definition: 'Stay authentic and honest — 100% real.', example: '“I’ll always keep it 100 with you.”', tags: ['authenticity', 'classic'], ...AXIS },
  { category: 'teen', term: 'standing on business', emoji: '🧍‍♂️', ageGroup: 'high_school', difficulty: 'hard', definition: 'Holding firm on your word or convictions — following through, no backing down.', example: '“She said she’d quit if they didn’t listen. She stood on business.”', tags: ['conviction'], ...AXIS },
  { category: 'teen', term: 'sleep on', emoji: '😴', ageGroup: 'high_school', difficulty: 'medium', definition: 'To underestimate or ignore something great. “Don’t sleep on it” = pay attention.', example: '“Y’all are sleeping on this album.”', tags: ['praise'], ...AXIS },
  { category: 'teen', term: 'smacks', emoji: '👄', ageGroup: 'middle', difficulty: 'easy', definition: 'Really good — food edition. Sibling of “slaps.”', example: '“This Chick-fil-A smacks.”', tags: ['food', 'praise'], ...AXIS },
  { category: 'teen', term: 'snack', emoji: '🍭', ageGroup: 'high_school', difficulty: 'easy', definition: 'An attractive person. Escalates to “whole meal.”', example: '“Lookin’ like a snack today.”', tags: ['attraction', 'food-scale'], ...AXIS },
  { category: 'teen', term: 'glow up', emoji: '🦋', ageGroup: 'high_school', difficulty: 'easy', definition: 'A dramatic transformation for the better — usually appearance, sometimes life.', example: '“Summer glow up went crazy.”', tags: ['transformation', 'compliment'], ...AXIS },
  { category: 'teen', term: 'slim thick', emoji: '⏳', ageGroup: 'college', difficulty: 'medium', definition: 'The culturally “ideal” hourglass body type — small waist, curves elsewhere. Worth discussing the body-image pressure it carries.', example: 'A body-type label all over fitness TikTok.', tags: ['body', 'parent-aware'], ...AXIS },

  // ---- Teen: identity & aesthetics ----
  { category: 'teen', term: 'aesthetic', emoji: '🎨', ageGroup: 'high_school', difficulty: 'easy', definition: 'A cohesive vibe or visual identity — noun and adjective. “That’s so aesthetic” = pleasingly styled.', example: '“Her room is a whole cottagecore aesthetic.”', tags: ['style', 'vibe'], ...AXIS },
  { category: 'teen', term: '-core / -coded', emoji: '🧬', ageGroup: 'high_school', difficulty: 'medium', definition: 'Suffixes for categorizing vibes: “cottagecore,” “2000s-core,” “Gilmore Girls-coded.” Anything can be a genre.', example: '“This town is so Halloween-coded.”', tags: ['suffix', 'vibe'], ...AXIS },
  { category: 'teen', term: 'emo', emoji: '🖤', ageGroup: 'high_school', difficulty: 'easy', definition: 'Feeling emotional (usually sad) — or the music/fashion subculture that never really died.', example: '“That movie ending has me so emo.”', tags: ['emotion', 'classic'], ...AXIS },
  { category: 'teen', term: 'fit', emoji: '👕', ageGroup: 'middle', difficulty: 'easy', definition: 'Outfit. “Fit check” = show us what you’re wearing. (In the UK it means attractive.)', example: '“Rate my fit for tonight.”', tags: ['fashion'], ...AXIS },
  { category: 'teen', term: 'whip', emoji: '🚙', ageGroup: 'high_school', difficulty: 'easy', definition: 'Car — especially a nice one.', example: '“New whip, who’s driving?”', tags: ['classic'], ...AXIS },
  { category: 'teen', term: 'adulting', emoji: '🧾', ageGroup: 'college', difficulty: 'easy', definition: 'Doing grown-up tasks (taxes, laundry, appointments) — announced with weary pride.', example: '“Made a dentist appointment myself. Adulting.”', tags: ['life', 'humor'], ...AXIS },
  { category: 'teen', term: 'vanilla', emoji: '🍦', ageGroup: 'high_school', difficulty: 'easy', definition: 'Plain, boring, unadventurous — basic’s blander cousin.', example: '“His playlist is so vanilla.”', tags: ['judgment'], ...AXIS },
  { category: 'teen', term: 'boujee', emoji: '💎', ageGroup: 'high_school', difficulty: 'easy', definition: 'Alt spelling of bougie — fancy, high-class, extra.', example: '“A $9 latte? Boujee.”', tags: ['class'], ...AXIS },
  { category: 'teen', term: 'boi', emoji: '🧢', ageGroup: 'middle', difficulty: 'easy', related: ['texting'], definition: 'Deliberate misspelling of “boy” — often in memes (“h boi”).', example: '“Look at this good boi.”', tags: ['spelling', 'meme'], ...AXIS },
  { category: 'teen', term: 'smol', emoji: '🐁', ageGroup: 'middle', difficulty: 'easy', related: ['texting'], definition: 'Adorably small. The misspelling adds the cuteness.', example: '“Look at the smol kitten!!”', tags: ['spelling', 'cute'], ...AXIS },
  { category: 'teen', term: 'boutta', emoji: '⏩', ageGroup: 'high_school', difficulty: 'easy', related: ['texting'], definition: '“About to.” Contraction of a contraction.', example: '“Boutta head out, need anything?”', tags: ['shorthand'], ...AXIS },
  { category: 'teen', term: 'BB', emoji: '👶', ageGroup: 'high_school', difficulty: 'easy', related: ['texting'], definition: '“Baby/babe” — said “bee bee,” mostly between friends.', example: '“Miss you bb!”', tags: ['affection'], ...AXIS },

  // ---- Teen: internet & fandom culture ----
  { category: 'teen', term: 'headcanon', emoji: '💭', ageGroup: 'high_school', difficulty: 'medium', definition: 'Your personal theory about fictional characters that isn’t official canon — but should be.', example: '“My headcanon is that Thor loves cats.”', tags: ['fandom'], ...AXIS },
  { category: 'teen', term: 'cancel', emoji: '❌', ageGroup: 'high_school', difficulty: 'easy', definition: 'To publicly drop someone/something as problematic. Ranges from serious accountability to joke (“you like pineapple pizza? canceled”).', example: '“He’s canceled after that take.”', tags: ['callout', 'dual-meaning'], ...AXIS },
  { category: 'teen', term: 'clout', emoji: '📸', ageGroup: 'high_school', difficulty: 'easy', definition: 'Social influence and popularity, especially online. “Clout chasing” = doing anything for attention.', example: '“He only posted that for clout.”', tags: ['social-media'], ...AXIS },
  { category: 'teen', term: 'subtweet', emoji: '🐦', ageGroup: 'college', difficulty: 'medium', related: ['texting'], definition: 'Calling someone out online without naming or tagging them — deniable public shade.', example: '“That post is 100% a subtweet about her ex.”', tags: ['social-media', 'drama'], ...AXIS },
  { category: 'teen', term: 'put on blast', emoji: '📢', ageGroup: 'high_school', difficulty: 'medium', definition: 'Exposing someone’s embarrassing business publicly.', example: '“She put the group chat on blast.”', tags: ['drama', 'callout'], ...AXIS },
  { category: 'teen', term: 'dragged', emoji: '🪢', ageGroup: 'high_school', difficulty: 'medium', definition: 'Mercilessly mocked or criticized, usually publicly online.', example: '“The comments dragged him for that take.”', tags: ['callout', 'drama'], ...AXIS },
  { category: 'teen', term: 'like my recent', emoji: '👍', ageGroup: 'middle', difficulty: 'medium', related: ['texting'], definition: 'A plea for engagement on your newest post. Related: LB (like back), FB (follow back). Widely seen as thirsty.', example: '“Story says ‘like my recent’ again.”', tags: ['social-media'], ...AXIS },
  { category: 'teen', term: 'Roman Empire', emoji: '🏛️', ageGroup: 'college', difficulty: 'medium', definition: 'The topic you inexplicably think about all the time — from the trend discovering men think about Rome weekly.', example: '“The Titanic is my Roman Empire.”', tags: ['meme', 'trend'], ...AXIS },
  { category: 'teen', term: 'biblically accurate', emoji: '👁️', ageGroup: 'high_school', difficulty: 'hard', definition: 'Uncanny, alarming, or horrifying — from art of “biblically accurate angels” (many wings, hundreds of eyes).', example: '“That AI render is biblically accurate.”', tags: ['meme', 'internet'], ...AXIS },
  { category: 'teen', term: 'cursed vs blessed', emoji: '⚖️', ageGroup: 'high_school', difficulty: 'medium', definition: 'The internet’s taxonomy of images: blessed = wholesome; cursed = deeply wrong. Axis logs “cursed” for bad-luck vibes too.', example: '“This image is either cursed or blessed and I can’t tell.”', tags: ['internet', 'meme'], ...AXIS },
  { category: 'teen', term: 'narrative', emoji: '📖', ageGroup: 'college', difficulty: 'medium', definition: '“I’d like to be excluded from this narrative” — Taylor Swift’s line, now shorthand for refusing involvement in drama.', example: '“Whatever this fight is, exclude me from the narrative.”', tags: ['drama', 'music'], ...AXIS },
  { category: 'teen', term: 'ASMR', emoji: '🎧', ageGroup: 'middle', difficulty: 'easy', definition: 'Videos of soft sounds (whispering, tapping) meant to trigger relaxing tingles. A massive video genre kids fall asleep to.', example: '“She watches slime ASMR for hours.”', tags: ['acronym', 'video-genre'], ...AXIS },
  { category: 'teen', term: 'IGL', emoji: '🎮', ageGroup: 'high_school', difficulty: 'hard', related: ['gaming'], definition: 'Per Axis: “in game life” — gamers referring to their in-game world. (In esports it also means “in-game leader.”)', example: '“That’s just my IGL, don’t judge.”', tags: ['acronym', 'gaming-culture'], ...AXIS },
  { category: 'teen', term: 'IYKWIM', emoji: '😏', ageGroup: 'high_school', difficulty: 'medium', related: ['texting'], definition: '“If you know what I mean” — the winking acronym.', example: '“They ‘studied’ all night, iykwim.”', tags: ['acronym', 'innuendo'], ...AXIS },

  // ---- Teen: food & money culture ----
  { category: 'teen', term: 'girl dinner', emoji: '🧀', ageGroup: 'college', difficulty: 'medium', definition: 'A no-cook meal of assembled snacks — from artful charcuterie to “fries, cheese, and half an energy bar.”', example: '“Crackers, pickles, and cheese: girl dinner.”', tags: ['food', 'trend'], ...AXIS },
  { category: 'teen', term: 'girl math', emoji: '🧮', ageGroup: 'college', difficulty: 'medium', definition: 'Playfully irrational money logic: “bought tickets months ago, so today it’s free.” An inside joke, occasionally weaponized.', example: '“Returning it = making money. Girl math.”', tags: ['money', 'humor', 'trend'], ...AXIS },
  { category: 'teen', term: 'let’s get this bread', emoji: '🥖', ageGroup: 'college', difficulty: 'medium', related: ['corporate'], definition: 'Hustle battle cry — bread/dough = money. Ironic-motivational.', example: '“6am shift. Let’s get this bread.”', tags: ['money', 'motivation', 'meme'], ...AXIS },
  { category: 'teen', term: 'big (mad/sad/brain)', emoji: '🔍', ageGroup: 'middle', difficulty: 'easy', definition: 'An intensifier prefix: big mad = furious, big sad = very sad, big brain = genius (often ironic).', example: '“He’s big mad about the score.”', tags: ['intensifier'], ...AXIS },
  { category: 'teen', term: 'GD', emoji: '🤬', ageGroup: 'high_school', difficulty: 'medium', related: ['texting'], definition: 'Abbreviated profanity (“god d***”) used as an intensifier in text.', example: '“It’s so gd hot today.”', tags: ['acronym', 'profanity'], ...AXIS },
  { category: 'teen', term: 'D', emoji: '🍆', ageGroup: 'high_school', difficulty: 'medium', definition: 'Short for a crude word for penis. Parents should recognize it in “she just wants the D.”', example: 'Single letters can carry meaning — context.', tags: ['sexual', 'parent-aware'], ...AXIS },
  { category: 'teen', term: 'gassing', emoji: '🎈', ageGroup: 'high_school', difficulty: 'easy', definition: 'Hyping someone up — inflating their confidence.', example: '“Always gassing up my friends before games.”', tags: ['compliment', 'support'], ...AXIS },
  { category: 'teen', term: 'clapped', emoji: '💥', ageGroup: 'high_school', difficulty: 'medium', related: ['gaming'], definition: 'Destroyed in a match — or, harshly, ugly. Both senses common.', example: '“We got clapped 5-0.”', tags: ['gaming-culture', 'insult'], ...AXIS },
  { category: 'teen', term: 'take the L', emoji: '🇱', ageGroup: 'high_school', difficulty: 'easy', related: ['gaming', 'texting'], definition: 'Accept the loss with (some) grace. Opposite: “that’s a W” (pronounced dub).', example: '“Wrong answer in front of everyone. Take the L.”', tags: ['loss', 'classic'], ...AXIS },
  { category: 'teen', term: 'hoco', emoji: '🏈', ageGroup: 'high_school', difficulty: 'easy', definition: 'Homecoming — the dance, the game, the proposals (“hoco proposals” are a whole genre).', example: '“Did you see how he asked her to hoco?”', tags: ['school', 'events'], ...AXIS },
  { category: 'teen', term: 'hop off', emoji: '✋', ageGroup: 'high_school', difficulty: 'medium', definition: 'Mind your own business; back off.', example: '“Why are you in my comments? Hop off.”', tags: ['dismissal'], ...AXIS },
  { category: 'teen', term: 'sip tea', emoji: '🍵', ageGroup: 'high_school', difficulty: 'medium', definition: 'Watch the drama without getting involved — spectate, don’t participate.', example: '“Not my fight. I’m just sipping tea.”', tags: ['drama', 'gossip'], ...AXIS },
  { category: 'teen', term: 'doing the most', emoji: '🎪', ageGroup: 'high_school', difficulty: 'easy', definition: 'Being excessively over the top when it wasn’t necessary.', example: '“A 40-slide presentation? You’re doing the most.”', tags: ['judgment', 'extra'], ...AXIS },
  { category: 'teen', term: 'boomer', emoji: '📻', ageGroup: 'high_school', difficulty: 'easy', definition: 'Anyone (of any age) with out-of-date takes or media taste. The generational dismissal, detached from actual generations.', example: '“He still uses Facebook. Boomer behavior.”', tags: ['generational'], ...AXIS },
  { category: 'teen', term: 'wig', emoji: '💇‍♀️', ageGroup: 'high_school', difficulty: 'hard', definition: 'So amazed your wig flew off — from drag culture. “Wig snatched” = completely blown away.', example: '“She hit that note and WIG.”', tags: ['drag-culture', 'hype'], ...AXIS },
  { category: 'teen', term: 'live / living', emoji: '🌟', ageGroup: 'high_school', difficulty: 'medium', definition: 'Something so good it makes you feel alive: “I’m living for this.”', example: '“Beach week with the squad — I’m LIVING.”', tags: ['hype'], ...AXIS },
  { category: 'teen', term: 'menty b', emoji: '🫠', ageGroup: 'college', difficulty: 'medium', definition: '“Mental breakdown,” cutely abbreviated (via Love Island). Usually joking — but worth an ear if it isn’t.', example: '“One more deadline and it’s a full menty b.”', tags: ['mental-health', 'humor'], ...AXIS },
  { category: 'teen', term: 'BDE', emoji: '😎', ageGroup: 'college', difficulty: 'hard', definition: 'Crude acronym for effortless, unbothered confidence (the kind that doesn’t need to prove anything). Explicit origin, mainstream usage.', example: '“He walked in like he owned it. BDE.”', tags: ['acronym', 'confidence', 'parent-aware'], ...AXIS },
  { category: 'teen', term: 'body', emoji: '🫣', ageGroup: 'college', difficulty: 'hard', related: ['safety'], definition: 'Objectifying slang: a “body” is someone you’ve been intimate with (see body count); “that’s a body” sexualizes a sweet gesture.', example: '“He made her a 4-hour playlist.” “That’s a body.”', tags: ['sexual', 'parent-aware'], ...AXIS },

  // ---- Radar catches (first live Bark/Axis scan, 2026-08-15) ----
  { category: 'teen', term: 'extra', emoji: '🎭', ageGroup: 'high_school', difficulty: 'easy', definition: 'Over the top, excessive, dramatic — more than the situation required.', example: '“A limo for a study session? So extra.”', tags: ['judgment', 'classic'], ...AXIS },
  { category: 'teen', term: 'catch these hands', emoji: '🤜', ageGroup: 'high_school', difficulty: 'medium', definition: 'A (usually joking) threat to fight: “you boutta catch these hands.”', example: '“Talk about my team again and catch these hands.”', tags: ['threat', 'humor'], ...AXIS },
  { category: 'teen', term: 'turnt', emoji: '🎉', ageGroup: 'high_school', difficulty: 'medium', definition: 'Hyped up, wild, energetic — “turnt up.” Bark notes it can also mean drunk/stoned; context matters.', example: '“The crowd was turnt after that touchdown.”', tags: ['party', 'dual-meaning'], sourceName: 'Bark — 2026 Teen Slang & Text Codes', sourceUrl: 'https://www.bark.us/blog/teen-text-speak-codes-every-parent-should-know/' },
  { category: 'teen', term: 'VSCO girl', emoji: '🐢', ageGroup: 'middle', difficulty: 'medium', definition: 'The scrunchies-Hydro-Flask-Crocs aesthetic named after the VSCO photo app. Dated now, but still referenced.', example: '“Full VSCO girl energy with that water bottle.”', tags: ['aesthetic', 'archetype'], sourceName: 'Bark — 2026 Teen Slang & Text Codes', sourceUrl: 'https://www.bark.us/blog/teen-text-speak-codes-every-parent-should-know/' },
  { category: 'texting', term: 'SH', emoji: '🤷', difficulty: 'medium', definition: '“Sh** happens.” Casual consolation. (In self-harm contexts SH can mean self-harm — context worth watching.)', example: '“Missed the bus, sh.”', tags: ['acronym', 'dual-meaning'], sourceName: 'Bark — 2026 Teen Slang & Text Codes', sourceUrl: 'https://www.bark.us/blog/teen-text-speak-codes-every-parent-should-know/' },
];
